using System; 
using TControls; 
using Newtonsoft.Json.Linq;

namespace TLogic.ARQODE_UI.ARQODE_UI
 { 
public class CInputDialog
 { 
public static String _JSON { get { return "ew0KICAiJHNjaGVtYSI6ICIuLlxcU2NoZW1hc1xcU2NoZW1hX2Jhc2VfY29udHJvbC5qc29uIiwNCiAgImRlc2NyaXB0aW9uIjogIiIsDQogICJWYXJpYWJsZXMiOiBbXSwNCiAgIkNvbnRyb2xzIjogWw0KICAgIHsNCiAgICAgICJHdWlkIjogIklucHV0RGlhbG9nIiwNCiAgICAgICJDbGFzc19QYXRoIjogIkFSUU9ERV9WSVNVQUxfRURJVE9SLkFSUU9ERV9VSS5JbnB1dERpYWxvZyIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5Gb3JtIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiMS4wLjAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNjQ5LA0KICAgICAgICAgICJIZWlnaHQiOiAxNzkNCiAgICAgICAgfSwNCiAgICAgICAgIlRleHQiOiAiRGF0YSBpbnB1dCIsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0NCiAgICAgIH0sDQogICAgICAiQ29udHJvbHMiOiBbDQogICAgICAgICJQQ29udGVuaWRvIiwNCiAgICAgICAgInBhbmVsMSINCiAgICAgIF0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlBDb250ZW5pZG8iLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuUGFuZWwiLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiRG9jayI6ICJGaWxsIiwNCiAgICAgICAgIlRhYkluZGV4IjogMSwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIkF1dG9TY3JvbGxNaW5TaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDAsDQogICAgICAgICAgIkhlaWdodCI6IDANCiAgICAgICAgfSwNCiAgICAgICAgIlZlcnRpY2FsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9LA0KICAgICAgICAiSG9yaXpvbnRhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfQ0KICAgICAgfSwNCiAgICAgICJDb250cm9scyI6IFsNCiAgICAgICAgIlBUZXh0Qm94IiwNCiAgICAgICAgIlBMYWJlbCINCiAgICAgIF0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlBUZXh0Qm94IiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlBhbmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjE1OTAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIkRvY2siOiAiRmlsbCIsDQogICAgICAgICJUYWJJbmRleCI6IDEsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0sDQogICAgICAgICJBdXRvU2Nyb2xsTWluU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiAwLA0KICAgICAgICAgICJIZWlnaHQiOiAwDQogICAgICAgIH0sDQogICAgICAgICJWZXJ0aWNhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfSwNCiAgICAgICAgIkhvcml6b250YWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0NCiAgICAgIH0sDQogICAgICAiQ29udHJvbHMiOiBbDQogICAgICAgICJ0ZXh0Qm94MSINCiAgICAgIF0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogInRleHRCb3gxIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlRleHRCb3giLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiA2MDUsDQogICAgICAgICAgIkhlaWdodCI6IDMyDQogICAgICAgIH0sDQogICAgICAgICJMb2NhdGlvbiI6IHsNCiAgICAgICAgICAiWCI6IDE2LA0KICAgICAgICAgICJZIjogMw0KICAgICAgICB9LA0KICAgICAgICAiTXVsdGlsaW5lIjogdHJ1ZQ0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiUExhYmVsIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlBhbmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjE1OTAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNjMzLA0KICAgICAgICAgICJIZWlnaHQiOiAzOA0KICAgICAgICB9LA0KICAgICAgICAiRG9jayI6ICJUb3AiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9LA0KICAgICAgICAiQXV0b1Njcm9sbE1pblNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMCwNCiAgICAgICAgICAiSGVpZ2h0IjogMA0KICAgICAgICB9LA0KICAgICAgICAiVmVydGljYWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0sDQogICAgICAgICJIb3Jpem9udGFsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkNvbnRyb2xzIjogWw0KICAgICAgICAiTGFiZWwxIg0KICAgICAgXQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiTGFiZWwxIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkxhYmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjE1OTAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNDIsDQogICAgICAgICAgIkhlaWdodCI6IDE2DQogICAgICAgIH0sDQogICAgICAgICJMb2NhdGlvbiI6IHsNCiAgICAgICAgICAiWCI6IDEzLA0KICAgICAgICAgICJZIjogMTMNCiAgICAgICAgfSwNCiAgICAgICAgIlRleHQiOiAibGFiZWwxIiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDAsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMCwNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIlRleHRBbGlnbiI6ICJUb3BMZWZ0Ig0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAicGFuZWwxIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlBhbmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjE1OTAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNjMzLA0KICAgICAgICAgICJIZWlnaHQiOiA1Ng0KICAgICAgICB9LA0KICAgICAgICAiRG9jayI6ICJCb3R0b20iLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9LA0KICAgICAgICAiQXV0b1Njcm9sbE1pblNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMCwNCiAgICAgICAgICAiSGVpZ2h0IjogMA0KICAgICAgICB9LA0KICAgICAgICAiVmVydGljYWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0sDQogICAgICAgICJIb3Jpem9udGFsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkNvbnRyb2xzIjogWw0KICAgICAgICAiQkNhbmNlbGFyIiwNCiAgICAgICAgIkJBY2VwdGFyIg0KICAgICAgXQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiQkNhbmNlbGFyIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkJ1dHRvbiIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDEwMSwNCiAgICAgICAgICAiSGVpZ2h0IjogMzANCiAgICAgICAgfSwNCiAgICAgICAgIkxvY2F0aW9uIjogew0KICAgICAgICAgICJYIjogNDEzLA0KICAgICAgICAgICJZIjogMTQNCiAgICAgICAgfSwNCiAgICAgICAgIlRhYkluZGV4IjogMiwNCiAgICAgICAgIlRleHQiOiAiQ2FuY2VsIiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfQ0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiQkFjZXB0YXIiLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuQnV0dG9uIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjE1OTAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMTAxLA0KICAgICAgICAgICJIZWlnaHQiOiAzMA0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiA1MjAsDQogICAgICAgICAgIlkiOiAxNA0KICAgICAgICB9LA0KICAgICAgICAiVGFiSW5kZXgiOiAxLA0KICAgICAgICAiVGV4dCI6ICJPSyIsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0NCiAgICAgIH0NCiAgICB9DQogIF0NCn0="; } }
public JObject MappedView { get { return JObject.Parse(System.Text.UTF8Encoding.UTF8.GetString(Convert.FromBase64String(_JSON))); } } 
public System.Windows.Forms.Form InputDialog;
public CView.CtrlStruct InputDialog_cstr;
public object InputDialog_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("ARQODE_UI.InputDialog")[var] = value; 
	return (object)view.CtrlVars("ARQODE_UI.InputDialog")[var];
}
public System.Windows.Forms.Panel PContenido;
public CView.CtrlStruct PContenido_cstr;
public object PContenido_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PContenido")[var] = value; 
	return (object)view.CtrlVars("PContenido")[var];
}
public System.Windows.Forms.Panel PTextBox;
public CView.CtrlStruct PTextBox_cstr;
public object PTextBox_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PTextBox")[var] = value; 
	return (object)view.CtrlVars("PTextBox")[var];
}
public System.Windows.Forms.TextBox textBox1;
public CView.CtrlStruct textBox1_cstr;
public object textBox1_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("textBox1")[var] = value; 
	return (object)view.CtrlVars("textBox1")[var];
}
public System.Windows.Forms.Panel PLabel;
public CView.CtrlStruct PLabel_cstr;
public object PLabel_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PLabel")[var] = value; 
	return (object)view.CtrlVars("PLabel")[var];
}
public System.Windows.Forms.Label Label1;
public CView.CtrlStruct Label1_cstr;
public object Label1_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("Label1")[var] = value; 
	return (object)view.CtrlVars("Label1")[var];
}
public System.Windows.Forms.Panel panel1;
public CView.CtrlStruct panel1_cstr;
public object panel1_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("panel1")[var] = value; 
	return (object)view.CtrlVars("panel1")[var];
}
public System.Windows.Forms.Button BCancelar;
public CView.CtrlStruct BCancelar_cstr;
public object BCancelar_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("BCancelar")[var] = value; 
	return (object)view.CtrlVars("BCancelar")[var];
}
public System.Windows.Forms.Button BAceptar;
public CView.CtrlStruct BAceptar_cstr;
public object BAceptar_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("BAceptar")[var] = value; 
	return (object)view.CtrlVars("BAceptar")[var];
}
public CView view; 
public CInputDialog (CViewsManager vm) { view = (vm.getFirstView("ARQODE_UI.InputDialog") != null)? vm.getFirstView("ARQODE_UI.InputDialog"): vm.AddView("ARQODE_UI.InputDialog");
InputDialog = (System.Windows.Forms.Form) view.getCtrl("ARQODE_UI.InputDialog");
InputDialog_cstr = view.getCtrlStruct("ARQODE_UI.InputDialog");
PContenido = (System.Windows.Forms.Panel) view.getCtrl("PContenido");
PContenido_cstr = view.getCtrlStruct("PContenido");
PTextBox = (System.Windows.Forms.Panel) view.getCtrl("PTextBox");
PTextBox_cstr = view.getCtrlStruct("PTextBox");
textBox1 = (System.Windows.Forms.TextBox) view.getCtrl("textBox1");
textBox1_cstr = view.getCtrlStruct("textBox1");
PLabel = (System.Windows.Forms.Panel) view.getCtrl("PLabel");
PLabel_cstr = view.getCtrlStruct("PLabel");
Label1 = (System.Windows.Forms.Label) view.getCtrl("Label1");
Label1_cstr = view.getCtrlStruct("Label1");
panel1 = (System.Windows.Forms.Panel) view.getCtrl("panel1");
panel1_cstr = view.getCtrlStruct("panel1");
BCancelar = (System.Windows.Forms.Button) view.getCtrl("BCancelar");
BCancelar_cstr = view.getCtrlStruct("BCancelar");
BAceptar = (System.Windows.Forms.Button) view.getCtrl("BAceptar");
BAceptar_cstr = view.getCtrlStruct("BAceptar");
 }}

}

