using System; 
using TControls; 
using Newtonsoft.Json.Linq;

namespace TLogic.ARQODE_UI.GestorProgramas
 { 
public class CVentanaProgramas
 { 
public static String _JSON { get { return "ew0KICAiJHNjaGVtYSI6ICIuLlxcU2NoZW1hc1xcU2NoZW1hX2Jhc2VfY29udHJvbC5qc29uIiwNCiAgImRlc2NyaXB0aW9uIjogIiIsDQogICJWYXJpYWJsZXMiOiBbDQogICAgIlByb2Nlc29zIHByb2dyYW1hIGFjdGl2byIsDQogICAgIk5hbWVzcGFjZSBwcm9ncmFtYSBhY3Rpdm8iLA0KICAgICJGaWxhIGFjdGl2YSBsaXN0YSBwcm9jZXNvcyIsDQogICAgIkFwcCBhY3RpdmEiLA0KICAgICJQcm9jZXNvIGRlIHByb2dyYW1hIGFjdGl2byIsDQogICAgIkhpc3TDs3JpY28gZGUgcHJvZ3JhbWFzIiwNCiAgICAiQXBsaWNhY2nDs24gYWN0aXZhIg0KICBdLA0KICAiQ29udHJvbHMiOiBbDQogICAgew0KICAgICAgIkd1aWQiOiAiVmVudGFuYVByb2dyYW1hcyIsDQogICAgICAiQ2xhc3NfUGF0aCI6ICJBUlFPREVfVklTVUFMX0VESVRPUi5BUlFPREVfVUkuVmVudGFuYVByb2dyYW1hcyIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5Gb3JtIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiMS4wLjAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMTEwMywNCiAgICAgICAgICAiSGVpZ2h0IjogNjg2DQogICAgICAgIH0sDQogICAgICAgICJUZXh0IjogIkFSUU9ERSBwcm9ncmFtIGVkaXRvciIsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0NCiAgICAgIH0sDQogICAgICAiQ29udHJvbHMiOiBbDQogICAgICAgICJQUHJvY2Vzc2VzIiwNCiAgICAgICAgIlBUb3AiLA0KICAgICAgICAiTWVudVRvcCINCiAgICAgIF0sDQogICAgICAiRXZlbnRzIjogew0KICAgICAgICAiTG9hZCI6ICJHZXN0acOzbiBkZSBQcm9ncmFtYXMuQ2FyZ2FyIHByb2dyYW1hcyINCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlBQcm9jZXNzZXMiLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuUGFuZWwiLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiRG9jayI6ICJGaWxsIiwNCiAgICAgICAgIlRhYkluZGV4IjogNCwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIkF1dG9TY3JvbGxNaW5TaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDAsDQogICAgICAgICAgIkhlaWdodCI6IDANCiAgICAgICAgfSwNCiAgICAgICAgIlZlcnRpY2FsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9LA0KICAgICAgICAiSG9yaXpvbnRhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfQ0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiUFRvcCIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5QYW5lbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDEwODcsDQogICAgICAgICAgIkhlaWdodCI6IDIyMg0KICAgICAgICB9LA0KICAgICAgICAiRG9jayI6ICJUb3AiLA0KICAgICAgICAiVGFiSW5kZXgiOiAzLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9LA0KICAgICAgICAiQXV0b1Njcm9sbE1pblNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMCwNCiAgICAgICAgICAiSGVpZ2h0IjogMA0KICAgICAgICB9LA0KICAgICAgICAiVmVydGljYWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0sDQogICAgICAgICJIb3Jpem9udGFsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkNvbnRyb2xzIjogWw0KICAgICAgICAiUExpc3RhUHJvY2Vzb3MiLA0KICAgICAgICAiUGFuZWxBcmJvbFByb2dyYW1hcyINCiAgICAgIF0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlBMaXN0YVByb2Nlc29zIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlBhbmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjE1OTAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIkRvY2siOiAiRmlsbCIsDQogICAgICAgICJUYWJJbmRleCI6IDMsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0sDQogICAgICAgICJBdXRvU2Nyb2xsTWluU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiAwLA0KICAgICAgICAgICJIZWlnaHQiOiAwDQogICAgICAgIH0sDQogICAgICAgICJWZXJ0aWNhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfSwNCiAgICAgICAgIkhvcml6b250YWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0NCiAgICAgIH0sDQogICAgICAiQ29udHJvbHMiOiBbDQogICAgICAgICJMaXN0YVByb2Nlc29zIg0KICAgICAgXSwNCiAgICAgICJFdmVudHMiOiB7DQogICAgICAgICJEb3VibGVDbGljayI6ICJHZXN0acOzbiBkZSBQcm9ncmFtYXMuUHJvY2Vzb3MgZGVsIHByb2dyYW1hLklyIGFsIHByb2Nlc28gYWN0aXZvIg0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiTGlzdGFQcm9jZXNvcyIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5EYXRhR3JpZFZpZXciLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiRG9jayI6ICJGaWxsIiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIkVkaXRNb2RlIjogIkVkaXRPbktleXN0cm9rZU9yRjIiLA0KICAgICAgICAiTXVsdGlTZWxlY3QiOiB0cnVlLA0KICAgICAgICAiU2VsZWN0aW9uTW9kZSI6ICJDZWxsU2VsZWN0IiwNCiAgICAgICAgIlNjcm9sbEJhcnMiOiAiQm90aCIsDQogICAgICAgICJBbGxvd1VzZXJUb0FkZFJvd3MiOiB0cnVlLA0KICAgICAgICAiQWxsb3dVc2VyVG9EZWxldGVSb3dzIjogdHJ1ZSwNCiAgICAgICAgIkFsbG93VXNlclRvT3JkZXJDb2x1bW5zIjogZmFsc2UsDQogICAgICAgICJBbGxvd1VzZXJUb1Jlc2l6ZUNvbHVtbnMiOiB0cnVlLA0KICAgICAgICAiQWxsb3dVc2VyVG9SZXNpemVSb3dzIjogdHJ1ZSwNCiAgICAgICAgIkNvbHVtbkhlYWRlcnNIZWlnaHRTaXplTW9kZSI6ICJBdXRvU2l6ZSIsDQogICAgICAgICJSb3dIZWFkZXJzV2lkdGhTaXplTW9kZSI6ICJFbmFibGVSZXNpemluZyIsDQogICAgICAgICJBbHRlcm5hdGluZ1Jvd3NEZWZhdWx0Q2VsbFN0eWxlIjoge30NCiAgICAgIH0sDQogICAgICAiRXZlbnRzIjogew0KICAgICAgICAiQ2VsbENvbnRlbnRDbGljayI6ICJHZXN0acOzbiBkZSBQcm9ncmFtYXMuRWRpdGFyIGPDs2RpZ28iLA0KICAgICAgICAiQ2VsbENsaWNrIjogIkdlc3Rpw7NuIGRlIFByb2dyYW1hcy5Qcm9jZXNvIGFjdGl2by5DYXJnYXIgcHJvY2VzbyBhY3Rpdm8iDQogICAgICB9DQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJjb250ZXh0TWVudV9MUHJvY2Vzb3MiLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuQ29udGV4dE1lbnVTdHJpcCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDEwNSwNCiAgICAgICAgICAiSGVpZ2h0IjogMTU4DQogICAgICAgIH0sDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAyLA0KICAgICAgICAgICJSaWdodCI6IDEsDQogICAgICAgICAgIkJvdHRvbSI6IDIsDQogICAgICAgICAgIkxlZnQiOiAzMw0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkV2ZW50cyI6IHsNCiAgICAgICAgImlyQWxQcm9jZXNvVG9vbFN0cmlwTWVudUl0ZW0iOiAiR2VzdGnDs24gZGUgUHJvZ3JhbWFzLlByb2Nlc29zIGRlbCBwcm9ncmFtYS5JciBhbCBwcm9jZXNvIGFjdGl2byIsDQogICAgICAgICJlbGltaW5hclRvb2xTdHJpcE1lbnVJdGVtMSI6ICJHZXN0acOzbiBkZSBQcm9ncmFtYXMuUHJvY2Vzb3MgZGVsIHByb2dyYW1hLkVsaW1pbmFyIHByb2Nlc28iLA0KICAgICAgICAic3ViaXJUb29sU3RyaXBNZW51SXRlbSI6ICJHZXN0acOzbiBkZSBQcm9ncmFtYXMuUHJvY2Vzb3MgZGVsIHByb2dyYW1hLlN1YmlyIHByb2Nlc28iLA0KICAgICAgICAiYmFqYXJUb29sU3RyaXBNZW51SXRlbSI6ICJHZXN0acOzbiBkZSBQcm9ncmFtYXMuUHJvY2Vzb3MgZGVsIHByb2dyYW1hLkJhamFyIHByb2Nlc28iLA0KICAgICAgICAiYnVzY2FyUmVmZXJlbmNpYXNUb29sU3RyaXBNZW51SXRlbSI6ICJHZXN0acOzbiBkZSBQcm9ncmFtYXMuSW5mb3JtYWNpw7NuLkJ1c2NhciByZWZlcmVuY2lhcyBhIHVuIHByb2Nlc28iLA0KICAgICAgICAiY2FsbHByb2dyYW1hUHJldmlhbWVudGVDb3J0YWRvVG9vbFN0cmlwTWVudUl0ZW0iOiAiR2VzdGnDs24gZGUgUHJvZ3JhbWFzLkdlc3Rpw7NuIGRlbCBjYWxsLkFzaWduYXIgY2FsbCBhbCBwcm9ncmFtYSBhY3Rpdm8iLA0KICAgICAgICAidmVyQ8OzZGlnb1Rvb2xTdHJpcE1lbnVJdGVtIjogIkdlc3Rpw7NuIGRlIFByb2dyYW1hcy5JbmZvcm1hY2nDs24uVmVyIGPDs2RpZ28gZGVsIHByb2Nlc28iLA0KICAgICAgICAiZWRpdGFyQ8OzZGlnb1Rvb2xTdHJpcE1lbnVJdGVtIjogIkdlc3Rpw7NuIGRlIFByb2dyYW1hcy5FbnZpYXIgY8OzZGlnbyBhIGVkaWNpw7NuIg0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiUGFuZWxBcmJvbFByb2dyYW1hcyIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5QYW5lbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDQwMCwNCiAgICAgICAgICAiSGVpZ2h0IjogMjIyDQogICAgICAgIH0sDQogICAgICAgICJEb2NrIjogIkxlZnQiLA0KICAgICAgICAiVGFiSW5kZXgiOiAxLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9LA0KICAgICAgICAiQXV0b1Njcm9sbE1pblNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMCwNCiAgICAgICAgICAiSGVpZ2h0IjogMA0KICAgICAgICB9LA0KICAgICAgICAiVmVydGljYWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0sDQogICAgICAgICJIb3Jpem9udGFsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkNvbnRyb2xzIjogWw0KICAgICAgICAiQXJib2xQcm9ncmFtYXMiDQogICAgICBdLA0KICAgICAgIkV2ZW50cyI6IHt9DQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJBcmJvbFByb2dyYW1hcyIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5UcmVlVmlldyIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJEb2NrIjogIkZpbGwiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkV2ZW50cyI6IHsNCiAgICAgICAgIkFmdGVyU2VsZWN0IjogIkdlc3Rpw7NuIGRlIFByb2dyYW1hcy5DYXJnYXIgc3VicHJvZ3JhbWFzIiwNCiAgICAgICAgIkFmdGVyRXhwYW5kIjogIkdlc3Rpw7NuIGRlIFByb2dyYW1hcy5DYXJnYXIgc3VicHJvZ3JhbWFzIg0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiY29udGV4dE1lbnVfUHJvZ3JhbWFzIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkNvbnRleHRNZW51U3RyaXAiLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiAxMTEsDQogICAgICAgICAgIkhlaWdodCI6IDE4MA0KICAgICAgICB9LA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMiwNCiAgICAgICAgICAiUmlnaHQiOiAxLA0KICAgICAgICAgICJCb3R0b20iOiAyLA0KICAgICAgICAgICJMZWZ0IjogMzMNCiAgICAgICAgfQ0KICAgICAgfSwNCiAgICAgICJFdmVudHMiOiB7DQogICAgICAgICJudWV2b1Rvb2xTdHJpcE1lbnVJdGVtIjogIkdlc3Rpw7NuIGRlIFByb2dyYW1hcy5Fc3RydWN0dXJhY2nDs24uQWJyaXIgZmljaGEgZGUgcHJvZ3JhbWEiLA0KICAgICAgICAiY29ydGFyVG9vbFN0cmlwTWVudUl0ZW0iOiAiR2VzdGnDs24gZGUgUHJvZ3JhbWFzLkVzdHJ1Y3R1cmFjacOzbi5Db3J0YXIiLA0KICAgICAgICAicGVnYXJUb29sU3RyaXBNZW51SXRlbSI6ICJHZXN0acOzbiBkZSBQcm9ncmFtYXMuRXN0cnVjdHVyYWNpw7NuLlBlZ2FyIiwNCiAgICAgICAgImVsaW1pbmFyVG9vbFN0cmlwTWVudUl0ZW0iOiAiR2VzdGnDs24gZGUgUHJvZ3JhbWFzLkVzdHJ1Y3R1cmFjacOzbi5FbGltaW5hciBwcm9ncmFtYSIsDQogICAgICAgICJudWV2YUNhcnBldGFUb29sU3RyaXBNZW51SXRlbSI6ICJHZXN0acOzbiBkZSBQcm9ncmFtYXMuRXN0cnVjdHVyYWNpw7NuLk51ZXZhIGNhcnBldGEiLA0KICAgICAgICAicmVub21icmFyVG9vbFN0cmlwTWVudUl0ZW0iOiAiR2VzdGnDs24gZGUgUHJvZ3JhbWFzLkVzdHJ1Y3R1cmFjacOzbi5SZW5vbWJyYXIiLA0KICAgICAgICAiYXNpZ25hckFUb29sU3RyaXBNZW51SXRlbSI6ICJHZXN0acOzbiBkZSBjb250cm9sZXMuQ2FyZ2FyIHZlbnRhbmEiLA0KICAgICAgICAiYnVzY2FyUmVmZXJlbmNpYXNUb29sU3RyaXBNZW51SXRlbTEiOiAiR2VzdGnDs24gZGUgUHJvZ3JhbWFzLkluZm9ybWFjacOzbi5CdXNjYXIgcmVmZXJlbmNpYXMgYSB1biBwcm9ncmFtYSIsDQogICAgICAgICJleHBvcnRhclByb2dyYW1hVG9vbFN0cmlwTWVudUl0ZW0iOiAiSW1wb3J0YXIgJiBFeHBvcnRhci5FeHBvcnRhciBwcm9ncmFtYSIsDQogICAgICAgICJpbXBvcnRhclByb2dyYW1hVG9vbFN0cmlwTWVudUl0ZW0iOiAiSW1wb3J0YXIgJiBFeHBvcnRhci5JbXBvcnRhciBwcm9ncmFtYSINCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIk1lbnVUb3AiLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuVG9vbFN0cmlwIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjE1OTAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMTA4NywNCiAgICAgICAgICAiSGVpZ2h0IjogMjUNCiAgICAgICAgfSwNCiAgICAgICAgIkRvY2siOiAiVG9wIiwNCiAgICAgICAgIlRleHQiOiAidG9vbFN0cmlwMSIsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAwLA0KICAgICAgICAgICJSaWdodCI6IDEsDQogICAgICAgICAgIkJvdHRvbSI6IDAsDQogICAgICAgICAgIkxlZnQiOiAwDQogICAgICAgIH0NCiAgICAgIH0NCiAgICB9DQogIF0sDQogICJPYmplY3RzIjogWw0KICAgIHsNCiAgICAgICJHdWlkIjogIk9wZW5YTUwgRG9jdW1lbnQiLA0KICAgICAgIkFzc2VtYmx5IjogIkFSUU9ERV9Db250cm9scy5BQ0NvbnRyb2xzLmRsbCIsDQogICAgICAiT2JqZWN0IE5hbWUiOiAiQVJRT0RFX0NvbnRyb2xzLk9wZW5YTUxEb2N1bWVudCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiT3BlblhNTCBEb2N1bWVudCIsDQogICAgICAiVmVyc2lvbiI6ICIxLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7fSwNCiAgICAgICJNZXRob2RzIjogew0KICAgICAgICAiQ3JlYXRlIHdvcmQgZG9jdW1lbnQiOiB7DQogICAgICAgICAgIk5hbWUiOiAiQ3JlYXRlV29yZERvY3VtZW50IiwNCiAgICAgICAgICAiUGFyYW1ldGVycyI6IHsNCiAgICAgICAgICAgICJmaWxlX3BhdGgiOiAiIiwNCiAgICAgICAgICAgICJydGZFbmNvZGVkU3RyaW5nIjogIiINCiAgICAgICAgICB9DQogICAgICAgIH0NCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIkNhcmdhciBhcmJvbCByZWN1cnNpdm8iLA0KICAgICAgIkFzc2VtYmx5IjogIkhlbHBDb250cm9scy5kbGwiLA0KICAgICAgIk9iamVjdCBOYW1lIjogIkhlbHBDb250cm9scy5DUmVsbGVuYXJBcmJvbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiRGV2dWVsdmUgdW4gYXJib2wgZGUgbm9kb3MgZGUgbGEgcnV0YSBkZSBjYXJwZXRhIGVudmlhZGEiLA0KICAgICAgIlZlcnNpb24iOiAiMS4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjoge30sDQogICAgICAiTWV0aG9kcyI6IHsNCiAgICAgICAgIkNyZWFyIGFyYm9sIGRlc2RlIGNhcnBldGEiOiB7DQogICAgICAgICAgIk5hbWUiOiAiRGVzZGVTaXN0ZW1hQXJjaGl2b3NfcmVjdXJzaXZvIiwNCiAgICAgICAgICAiUGFyYW1ldGVycyI6IHsNCiAgICAgICAgICAgICJwYXRoIjogIiIsDQogICAgICAgICAgICAiT21pdF9maWxlc19hbmRfZGlyX2xpc3QiOiAiIg0KICAgICAgICAgIH0NCiAgICAgICAgfSwNCiAgICAgICAgIkNyZWFyIGxpc3RhIGRlIG5vZG9zIGhvamEgZGVsIMOhcmJvbCI6IHsNCiAgICAgICAgICAiTmFtZSI6ICJDcmVhckxpc3RhTm9kb3NIb2phIiwNCiAgICAgICAgICAiUGFyYW1ldGVycyI6IHsNCiAgICAgICAgICAgICJhcmJvbF9vcmlnZW4iOiAiIg0KICAgICAgICAgIH0NCiAgICAgICAgfQ0KICAgICAgfQ0KICAgIH0NCiAgXQ0KfQ=="; } }
public JObject MappedView { get { return JObject.Parse(System.Text.UTF8Encoding.UTF8.GetString(Convert.FromBase64String(_JSON))); } } 
public System.Windows.Forms.Form VentanaProgramas;
public CView.CtrlStruct VentanaProgramas_cstr;
public object VentanaProgramas_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("GestorProgramas.VentanaProgramas")[var] = value; 
	return (object)view.CtrlVars("GestorProgramas.VentanaProgramas")[var];
}
public System.Windows.Forms.Panel PProcesses;
public CView.CtrlStruct PProcesses_cstr;
public object PProcesses_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PProcesses")[var] = value; 
	return (object)view.CtrlVars("PProcesses")[var];
}
public System.Windows.Forms.Panel PTop;
public CView.CtrlStruct PTop_cstr;
public object PTop_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PTop")[var] = value; 
	return (object)view.CtrlVars("PTop")[var];
}
public System.Windows.Forms.Panel PListaProcesos;
public CView.CtrlStruct PListaProcesos_cstr;
public object PListaProcesos_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PListaProcesos")[var] = value; 
	return (object)view.CtrlVars("PListaProcesos")[var];
}
public System.Windows.Forms.DataGridView ListaProcesos;
public CView.CtrlStruct ListaProcesos_cstr;
public object ListaProcesos_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("ListaProcesos")[var] = value; 
	return (object)view.CtrlVars("ListaProcesos")[var];
}
public System.Windows.Forms.ContextMenuStrip contextMenu_LProcesos;
public CView.CtrlStruct contextMenu_LProcesos_cstr;
public object contextMenu_LProcesos_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("contextMenu_LProcesos")[var] = value; 
	return (object)view.CtrlVars("contextMenu_LProcesos")[var];
}
public System.Windows.Forms.Panel PanelArbolProgramas;
public CView.CtrlStruct PanelArbolProgramas_cstr;
public object PanelArbolProgramas_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PanelArbolProgramas")[var] = value; 
	return (object)view.CtrlVars("PanelArbolProgramas")[var];
}
public System.Windows.Forms.TreeView ArbolProgramas;
public CView.CtrlStruct ArbolProgramas_cstr;
public object ArbolProgramas_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("ArbolProgramas")[var] = value; 
	return (object)view.CtrlVars("ArbolProgramas")[var];
}
public System.Windows.Forms.ContextMenuStrip contextMenu_Programas;
public CView.CtrlStruct contextMenu_Programas_cstr;
public object contextMenu_Programas_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("contextMenu_Programas")[var] = value; 
	return (object)view.CtrlVars("contextMenu_Programas")[var];
}
public System.Windows.Forms.ToolStrip MenuTop;
public CView.CtrlStruct MenuTop_cstr;
public object MenuTop_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("MenuTop")[var] = value; 
	return (object)view.CtrlVars("MenuTop")[var];
}
public object Procesos_programa_activo { get { return (view.vars.ContainsKey("Procesos programa activo"))? (object)view.vars["Procesos programa activo"]: null; } set { view.vars["Procesos programa activo"] = value; } }
public object Namespace_programa_activo { get { return (view.vars.ContainsKey("Namespace programa activo"))? (object)view.vars["Namespace programa activo"]: null; } set { view.vars["Namespace programa activo"] = value; } }
public object Fila_activa_lista_procesos { get { return (view.vars.ContainsKey("Fila activa lista procesos"))? (object)view.vars["Fila activa lista procesos"]: null; } set { view.vars["Fila activa lista procesos"] = value; } }
public object App_activa { get { return (view.vars.ContainsKey("App activa"))? (object)view.vars["App activa"]: null; } set { view.vars["App activa"] = value; } }
public object Proceso_de_programa_activo { get { return (view.vars.ContainsKey("Proceso de programa activo"))? (object)view.vars["Proceso de programa activo"]: null; } set { view.vars["Proceso de programa activo"] = value; } }
public object Historico_de_programas { get { return (view.vars.ContainsKey("Histórico de programas"))? (object)view.vars["Histórico de programas"]: null; } set { view.vars["Histórico de programas"] = value; } }
public object Aplicacion_activa { get { return (view.vars.ContainsKey("Aplicación activa"))? (object)view.vars["Aplicación activa"]: null; } set { view.vars["Aplicación activa"] = value; } }
public o_OpenXML_Document OpenXML_Document;
public o_Cargar_arbol_recursivo Cargar_arbol_recursivo;
public CView view; 
public CVentanaProgramas (CViewsManager vm) { view = (vm.getFirstView("GestorProgramas.VentanaProgramas") != null)? vm.getFirstView("GestorProgramas.VentanaProgramas"): vm.AddView("GestorProgramas.VentanaProgramas");
VentanaProgramas = (System.Windows.Forms.Form) view.getCtrl("GestorProgramas.VentanaProgramas");
VentanaProgramas_cstr = view.getCtrlStruct("GestorProgramas.VentanaProgramas");
PProcesses = (System.Windows.Forms.Panel) view.getCtrl("PProcesses");
PProcesses_cstr = view.getCtrlStruct("PProcesses");
PTop = (System.Windows.Forms.Panel) view.getCtrl("PTop");
PTop_cstr = view.getCtrlStruct("PTop");
PListaProcesos = (System.Windows.Forms.Panel) view.getCtrl("PListaProcesos");
PListaProcesos_cstr = view.getCtrlStruct("PListaProcesos");
ListaProcesos = (System.Windows.Forms.DataGridView) view.getCtrl("ListaProcesos");
ListaProcesos_cstr = view.getCtrlStruct("ListaProcesos");
contextMenu_LProcesos = (System.Windows.Forms.ContextMenuStrip) view.getCtrl("contextMenu_LProcesos");
contextMenu_LProcesos_cstr = view.getCtrlStruct("contextMenu_LProcesos");
PanelArbolProgramas = (System.Windows.Forms.Panel) view.getCtrl("PanelArbolProgramas");
PanelArbolProgramas_cstr = view.getCtrlStruct("PanelArbolProgramas");
ArbolProgramas = (System.Windows.Forms.TreeView) view.getCtrl("ArbolProgramas");
ArbolProgramas_cstr = view.getCtrlStruct("ArbolProgramas");
contextMenu_Programas = (System.Windows.Forms.ContextMenuStrip) view.getCtrl("contextMenu_Programas");
contextMenu_Programas_cstr = view.getCtrlStruct("contextMenu_Programas");
MenuTop = (System.Windows.Forms.ToolStrip) view.getCtrl("MenuTop");
MenuTop_cstr = view.getCtrlStruct("MenuTop");
OpenXML_Document = new o_OpenXML_Document(view);
Cargar_arbol_recursivo = new o_Cargar_arbol_recursivo(view);
 }}
public class o_OpenXML_Document
{
CView view = null;
public CView.ObjStruct Obj_str { get { return view.getObjStruct("OpenXML Document"); } }
public o_OpenXML_Document(CView v) { view = v; }
public object Create_word_document()
{
return view.MethodCall("OpenXML Document", "Create word document", null);
}
public object Create_word_document(object file_path, object rtfEncodedString)
{
return view.MethodCall("OpenXML Document", "Create word document", new object[] { file_path, rtfEncodedString });
}
}
public class o_Cargar_arbol_recursivo
{
CView view = null;
public CView.ObjStruct Obj_str { get { return view.getObjStruct("Cargar arbol recursivo"); } }
public o_Cargar_arbol_recursivo(CView v) { view = v; }
public object Crear_arbol_desde_carpeta()
{
return view.MethodCall("Cargar arbol recursivo", "Crear arbol desde carpeta", null);
}
public object Crear_arbol_desde_carpeta(object path, object Omit_files_and_dir_list)
{
return view.MethodCall("Cargar arbol recursivo", "Crear arbol desde carpeta", new object[] { path, Omit_files_and_dir_list });
}
public object Crear_lista_de_nodos_hoja_del_arbol()
{
return view.MethodCall("Cargar arbol recursivo", "Crear lista de nodos hoja del árbol", null);
}
public object Crear_lista_de_nodos_hoja_del_arbol(object arbol_origen)
{
return view.MethodCall("Cargar arbol recursivo", "Crear lista de nodos hoja del árbol", new object[] { arbol_origen });
}
}

}

