using System; 
using TControls; 
using Newtonsoft.Json.Linq;

namespace TLogic.ARQODE_UI.GestorProcesos
 { 
public class CFormProceso
 { 
public static String _JSON { get { return "ew0KICAiJHNjaGVtYSI6ICIuLlxcU2NoZW1hc1xcU2NoZW1hX2Jhc2VfY29udHJvbC5qc29uIiwNCiAgImRlc2NyaXB0aW9uIjogIiIsDQogICJWYXJpYWJsZXMiOiBbDQogICAgIlByb2Nlc28iLA0KICAgICJGaWNoZXJvUHJvY2VzbyIsDQogICAgIk5hbWVzcGFjZSBwcm9ncmFtYSBhY3Rpdm8iDQogIF0sDQogICJDb250cm9scyI6IFsNCiAgICB7DQogICAgICAiR3VpZCI6ICJGb3JtUHJvY2VzbyIsDQogICAgICAiQ2xhc3NfUGF0aCI6ICJBUlFPREVfVklTVUFMX0VESVRPUi5BUlFPREVfVUkuRm9ybVByb2Nlc28iLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuVXNlckNvbnRyb2wiLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICIxLjAuMC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiA3NjcsDQogICAgICAgICAgIkhlaWdodCI6IDU0NA0KICAgICAgICB9LA0KICAgICAgICAiVGV4dCI6ICJGb3JtUHJvY2VzbyIsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0NCiAgICAgIH0sDQogICAgICAiQ29udHJvbHMiOiBbDQogICAgICAgICJQSW5mbyINCiAgICAgIF0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlBJbmZvIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlBhbmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIkRvY2siOiAiRmlsbCIsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0sDQogICAgICAgICJBdXRvU2Nyb2xsTWluU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiAwLA0KICAgICAgICAgICJIZWlnaHQiOiAwDQogICAgICAgIH0sDQogICAgICAgICJWZXJ0aWNhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfSwNCiAgICAgICAgIkhvcml6b250YWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0NCiAgICAgIH0sDQogICAgICAiQ29udHJvbHMiOiBbDQogICAgICAgICJCR3VhcmRhciIsDQogICAgICAgICJsYWJlbDgiLA0KICAgICAgICAiVEJEZWZhdWx0X0NvbmZpZ3VyYXRpb24iLA0KICAgICAgICAiVEJDb25maWd1cmF0aW9uIiwNCiAgICAgICAgImxhYmVsNyIsDQogICAgICAgICJUQk91dHB1dHMiLA0KICAgICAgICAiVEJJbnB1dHMiLA0KICAgICAgICAibGFiZWw2IiwNCiAgICAgICAgImxhYmVsNSIsDQogICAgICAgICJMR1VJRCIsDQogICAgICAgICJUQkRlc2NyaXB0aW9uIiwNCiAgICAgICAgIlRCTmFtZSIsDQogICAgICAgICJUQlZlcnNpb24iLA0KICAgICAgICAibGFiZWw0IiwNCiAgICAgICAgImxhYmVsMyIsDQogICAgICAgICJsYWJlbDIiLA0KICAgICAgICAibGFiZWwxIg0KICAgICAgXQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiQkd1YXJkYXIiLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuQnV0dG9uIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMTU2LA0KICAgICAgICAgICJIZWlnaHQiOiAzMw0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiA1OTksDQogICAgICAgICAgIlkiOiA4DQogICAgICAgIH0sDQogICAgICAgICJUYWJJbmRleCI6IDUsDQogICAgICAgICJUZXh0IjogIlNhdmUiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkV2ZW50cyI6IHsNCiAgICAgICAgIkNsaWNrIjogIkdlc3Rpw7NuIGRlIFByb2Nlc29zLkd1YXJkYXIgZGF0b3MgcHJvY2VzbyINCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogImxhYmVsOCIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5MYWJlbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xMDg3LjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDk4LA0KICAgICAgICAgICJIZWlnaHQiOiAzNQ0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiAyNCwNCiAgICAgICAgICAiWSI6IDQ3NA0KICAgICAgICB9LA0KICAgICAgICAiVGFiSW5kZXgiOiAxMiwNCiAgICAgICAgIlRleHQiOiAiRGVmYXVsdCBjb25maWd1cmF0aW9uOiIsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAwLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDAsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0sDQogICAgICAgICJUZXh0QWxpZ24iOiAiVG9wUmlnaHQiDQogICAgICB9DQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJUQkRlZmF1bHRfQ29uZmlndXJhdGlvbiIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5UZXh0Qm94IiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNjI3LA0KICAgICAgICAgICJIZWlnaHQiOiA2MQ0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiAxMjgsDQogICAgICAgICAgIlkiOiA0NzENCiAgICAgICAgfSwNCiAgICAgICAgIlRhYkluZGV4IjogNiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIk11bHRpbGluZSI6IHRydWUNCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlRCQ29uZmlndXJhdGlvbiIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5UZXh0Qm94IiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNjI3LA0KICAgICAgICAgICJIZWlnaHQiOiA5Mw0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiAxMzEsDQogICAgICAgICAgIlkiOiAzNzINCiAgICAgICAgfSwNCiAgICAgICAgIlRhYkluZGV4IjogNCwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIk11bHRpbGluZSI6IHRydWUNCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogImxhYmVsNyIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5MYWJlbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xMDg3LjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDk4LA0KICAgICAgICAgICJIZWlnaHQiOiAxNg0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiAyNiwNCiAgICAgICAgICAiWSI6IDM4Ng0KICAgICAgICB9LA0KICAgICAgICAiVGFiSW5kZXgiOiA5LA0KICAgICAgICAiVGV4dCI6ICJDb25maWd1cmF0aW9uOiIsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAwLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDAsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0sDQogICAgICAgICJUZXh0QWxpZ24iOiAiVG9wTGVmdCINCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlRCT3V0cHV0cyIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5UZXh0Qm94IiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNjI3LA0KICAgICAgICAgICJIZWlnaHQiOiA5Nw0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiAxMzEsDQogICAgICAgICAgIlkiOiAyNjkNCiAgICAgICAgfSwNCiAgICAgICAgIlRhYkluZGV4IjogMywNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIk11bHRpbGluZSI6IHRydWUNCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlRCSW5wdXRzIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlRleHRCb3giLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTA4Ny4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiA2MjcsDQogICAgICAgICAgIkhlaWdodCI6IDkxDQogICAgICAgIH0sDQogICAgICAgICJMb2NhdGlvbiI6IHsNCiAgICAgICAgICAiWCI6IDEzMCwNCiAgICAgICAgICAiWSI6IDE3Mg0KICAgICAgICB9LA0KICAgICAgICAiVGFiSW5kZXgiOiAyLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9LA0KICAgICAgICAiTXVsdGlsaW5lIjogdHJ1ZQ0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAibGFiZWw2IiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkxhYmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNjAsDQogICAgICAgICAgIkhlaWdodCI6IDE2DQogICAgICAgIH0sDQogICAgICAgICJMb2NhdGlvbiI6IHsNCiAgICAgICAgICAiWCI6IDY1LA0KICAgICAgICAgICJZIjogMjcyDQogICAgICAgIH0sDQogICAgICAgICJUYWJJbmRleCI6IDYsDQogICAgICAgICJUZXh0IjogIk91dHB1dHM6IiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDAsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMCwNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIlRleHRBbGlnbiI6ICJUb3BMZWZ0Ig0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAibGFiZWw1IiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkxhYmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNTAsDQogICAgICAgICAgIkhlaWdodCI6IDE2DQogICAgICAgIH0sDQogICAgICAgICJMb2NhdGlvbiI6IHsNCiAgICAgICAgICAiWCI6IDc0LA0KICAgICAgICAgICJZIjogMTc1DQogICAgICAgIH0sDQogICAgICAgICJUYWJJbmRleCI6IDQsDQogICAgICAgICJUZXh0IjogIklucHV0czoiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMCwNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAwLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9LA0KICAgICAgICAiVGV4dEFsaWduIjogIlRvcExlZnQiDQogICAgICB9DQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJMR1VJRCIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5MYWJlbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xMDg3LjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDQ0NCwNCiAgICAgICAgICAiSGVpZ2h0IjogNDMNCiAgICAgICAgfSwNCiAgICAgICAgIkxvY2F0aW9uIjogew0KICAgICAgICAgICJYIjogMTI4LA0KICAgICAgICAgICJZIjogMjENCiAgICAgICAgfSwNCiAgICAgICAgIlRhYkluZGV4IjogMiwNCiAgICAgICAgIlRleHQiOiAiUFJPQ0VTU19HVUlEIiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDAsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMCwNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIlRleHRBbGlnbiI6ICJUb3BMZWZ0Ig0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiVEJEZXNjcmlwdGlvbiIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5UZXh0Qm94IiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNjI3LA0KICAgICAgICAgICJIZWlnaHQiOiA1OA0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiAxMzAsDQogICAgICAgICAgIlkiOiAxMDgNCiAgICAgICAgfSwNCiAgICAgICAgIlRhYkluZGV4IjogMSwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIk11bHRpbGluZSI6IHRydWUNCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlRCTmFtZSIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5UZXh0Qm94IiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNjI3LA0KICAgICAgICAgICJIZWlnaHQiOiAyMg0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiAxMzAsDQogICAgICAgICAgIlkiOiA4MQ0KICAgICAgICB9LA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9DQogICAgICB9DQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJUQlZlcnNpb24iLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuVGV4dEJveCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xMDg3LjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDEwMCwNCiAgICAgICAgICAiSGVpZ2h0IjogMjINCiAgICAgICAgfSwNCiAgICAgICAgIkxvY2F0aW9uIjogew0KICAgICAgICAgICJYIjogNjU1LA0KICAgICAgICAgICJZIjogNDcNCiAgICAgICAgfSwNCiAgICAgICAgIlRhYkluZGV4IjogNywNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfQ0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAibGFiZWw0IiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkxhYmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNTksDQogICAgICAgICAgIkhlaWdodCI6IDE2DQogICAgICAgIH0sDQogICAgICAgICJMb2NhdGlvbiI6IHsNCiAgICAgICAgICAiWCI6IDU5NCwNCiAgICAgICAgICAiWSI6IDQ4DQogICAgICAgIH0sDQogICAgICAgICJUZXh0IjogIlZlcnNpb246IiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDAsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMCwNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIlRleHRBbGlnbiI6ICJUb3BMZWZ0Ig0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAibGFiZWwzIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkxhYmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogODMsDQogICAgICAgICAgIkhlaWdodCI6IDE2DQogICAgICAgIH0sDQogICAgICAgICJMb2NhdGlvbiI6IHsNCiAgICAgICAgICAiWCI6IDQ4LA0KICAgICAgICAgICJZIjogMTExDQogICAgICAgIH0sDQogICAgICAgICJUZXh0IjogIkRlc2NyaXB0aW9uOiIsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAwLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDAsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0sDQogICAgICAgICJUZXh0QWxpZ24iOiAiVG9wTGVmdCINCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogImxhYmVsMiIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5MYWJlbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xMDg3LjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDQ5LA0KICAgICAgICAgICJIZWlnaHQiOiAxNg0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiA4MiwNCiAgICAgICAgICAiWSI6IDg0DQogICAgICAgIH0sDQogICAgICAgICJUZXh0IjogIk5hbWU6IiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDAsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMCwNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIlRleHRBbGlnbiI6ICJUb3BMZWZ0Ig0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAibGFiZWwxIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkxhYmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNDQsDQogICAgICAgICAgIkhlaWdodCI6IDE2DQogICAgICAgIH0sDQogICAgICAgICJMb2NhdGlvbiI6IHsNCiAgICAgICAgICAiWCI6IDg4LA0KICAgICAgICAgICJZIjogMjENCiAgICAgICAgfSwNCiAgICAgICAgIlRleHQiOiAiR1VJRDoiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMCwNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAwLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9LA0KICAgICAgICAiVGV4dEFsaWduIjogIlRvcExlZnQiDQogICAgICB9DQogICAgfQ0KICBdDQp9"; } }
public JObject MappedView { get { return JObject.Parse(System.Text.UTF8Encoding.UTF8.GetString(Convert.FromBase64String(_JSON))); } } 
public System.Windows.Forms.UserControl FormProceso;
public CView.CtrlStruct FormProceso_cstr;
public object FormProceso_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("GestorProcesos.FormProceso")[var] = value; 
	return (object)view.CtrlVars("GestorProcesos.FormProceso")[var];
}
public System.Windows.Forms.Panel PInfo;
public CView.CtrlStruct PInfo_cstr;
public object PInfo_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PInfo")[var] = value; 
	return (object)view.CtrlVars("PInfo")[var];
}
public System.Windows.Forms.Button BGuardar;
public CView.CtrlStruct BGuardar_cstr;
public object BGuardar_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("BGuardar")[var] = value; 
	return (object)view.CtrlVars("BGuardar")[var];
}
public System.Windows.Forms.Label label8;
public CView.CtrlStruct label8_cstr;
public object label8_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("label8")[var] = value; 
	return (object)view.CtrlVars("label8")[var];
}
public System.Windows.Forms.TextBox TBDefault_Configuration;
public CView.CtrlStruct TBDefault_Configuration_cstr;
public object TBDefault_Configuration_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("TBDefault_Configuration")[var] = value; 
	return (object)view.CtrlVars("TBDefault_Configuration")[var];
}
public System.Windows.Forms.TextBox TBConfiguration;
public CView.CtrlStruct TBConfiguration_cstr;
public object TBConfiguration_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("TBConfiguration")[var] = value; 
	return (object)view.CtrlVars("TBConfiguration")[var];
}
public System.Windows.Forms.Label label7;
public CView.CtrlStruct label7_cstr;
public object label7_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("label7")[var] = value; 
	return (object)view.CtrlVars("label7")[var];
}
public System.Windows.Forms.TextBox TBOutputs;
public CView.CtrlStruct TBOutputs_cstr;
public object TBOutputs_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("TBOutputs")[var] = value; 
	return (object)view.CtrlVars("TBOutputs")[var];
}
public System.Windows.Forms.TextBox TBInputs;
public CView.CtrlStruct TBInputs_cstr;
public object TBInputs_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("TBInputs")[var] = value; 
	return (object)view.CtrlVars("TBInputs")[var];
}
public System.Windows.Forms.Label label6;
public CView.CtrlStruct label6_cstr;
public object label6_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("label6")[var] = value; 
	return (object)view.CtrlVars("label6")[var];
}
public System.Windows.Forms.Label label5;
public CView.CtrlStruct label5_cstr;
public object label5_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("label5")[var] = value; 
	return (object)view.CtrlVars("label5")[var];
}
public System.Windows.Forms.Label LGUID;
public CView.CtrlStruct LGUID_cstr;
public object LGUID_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("LGUID")[var] = value; 
	return (object)view.CtrlVars("LGUID")[var];
}
public System.Windows.Forms.TextBox TBDescription;
public CView.CtrlStruct TBDescription_cstr;
public object TBDescription_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("TBDescription")[var] = value; 
	return (object)view.CtrlVars("TBDescription")[var];
}
public System.Windows.Forms.TextBox TBName;
public CView.CtrlStruct TBName_cstr;
public object TBName_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("TBName")[var] = value; 
	return (object)view.CtrlVars("TBName")[var];
}
public System.Windows.Forms.TextBox TBVersion;
public CView.CtrlStruct TBVersion_cstr;
public object TBVersion_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("TBVersion")[var] = value; 
	return (object)view.CtrlVars("TBVersion")[var];
}
public System.Windows.Forms.Label label4;
public CView.CtrlStruct label4_cstr;
public object label4_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("label4")[var] = value; 
	return (object)view.CtrlVars("label4")[var];
}
public System.Windows.Forms.Label label3;
public CView.CtrlStruct label3_cstr;
public object label3_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("label3")[var] = value; 
	return (object)view.CtrlVars("label3")[var];
}
public System.Windows.Forms.Label label2;
public CView.CtrlStruct label2_cstr;
public object label2_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("label2")[var] = value; 
	return (object)view.CtrlVars("label2")[var];
}
public System.Windows.Forms.Label label1;
public CView.CtrlStruct label1_cstr;
public object label1_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("label1")[var] = value; 
	return (object)view.CtrlVars("label1")[var];
}
public object Proceso { get { return (view.vars.ContainsKey("Proceso"))? (object)view.vars["Proceso"]: null; } set { view.vars["Proceso"] = value; } }
public object FicheroProceso { get { return (view.vars.ContainsKey("FicheroProceso"))? (object)view.vars["FicheroProceso"]: null; } set { view.vars["FicheroProceso"] = value; } }
public object Namespace_programa_activo { get { return (view.vars.ContainsKey("Namespace programa activo"))? (object)view.vars["Namespace programa activo"]: null; } set { view.vars["Namespace programa activo"] = value; } }
public CView view; 
public CFormProceso (CViewsManager vm) { view = (vm.getFirstView("GestorProcesos.FormProceso") != null)? vm.getFirstView("GestorProcesos.FormProceso"): vm.AddView("GestorProcesos.FormProceso");
FormProceso = (System.Windows.Forms.UserControl) view.getCtrl("GestorProcesos.FormProceso");
FormProceso_cstr = view.getCtrlStruct("GestorProcesos.FormProceso");
PInfo = (System.Windows.Forms.Panel) view.getCtrl("PInfo");
PInfo_cstr = view.getCtrlStruct("PInfo");
BGuardar = (System.Windows.Forms.Button) view.getCtrl("BGuardar");
BGuardar_cstr = view.getCtrlStruct("BGuardar");
label8 = (System.Windows.Forms.Label) view.getCtrl("label8");
label8_cstr = view.getCtrlStruct("label8");
TBDefault_Configuration = (System.Windows.Forms.TextBox) view.getCtrl("TBDefault_Configuration");
TBDefault_Configuration_cstr = view.getCtrlStruct("TBDefault_Configuration");
TBConfiguration = (System.Windows.Forms.TextBox) view.getCtrl("TBConfiguration");
TBConfiguration_cstr = view.getCtrlStruct("TBConfiguration");
label7 = (System.Windows.Forms.Label) view.getCtrl("label7");
label7_cstr = view.getCtrlStruct("label7");
TBOutputs = (System.Windows.Forms.TextBox) view.getCtrl("TBOutputs");
TBOutputs_cstr = view.getCtrlStruct("TBOutputs");
TBInputs = (System.Windows.Forms.TextBox) view.getCtrl("TBInputs");
TBInputs_cstr = view.getCtrlStruct("TBInputs");
label6 = (System.Windows.Forms.Label) view.getCtrl("label6");
label6_cstr = view.getCtrlStruct("label6");
label5 = (System.Windows.Forms.Label) view.getCtrl("label5");
label5_cstr = view.getCtrlStruct("label5");
LGUID = (System.Windows.Forms.Label) view.getCtrl("LGUID");
LGUID_cstr = view.getCtrlStruct("LGUID");
TBDescription = (System.Windows.Forms.TextBox) view.getCtrl("TBDescription");
TBDescription_cstr = view.getCtrlStruct("TBDescription");
TBName = (System.Windows.Forms.TextBox) view.getCtrl("TBName");
TBName_cstr = view.getCtrlStruct("TBName");
TBVersion = (System.Windows.Forms.TextBox) view.getCtrl("TBVersion");
TBVersion_cstr = view.getCtrlStruct("TBVersion");
label4 = (System.Windows.Forms.Label) view.getCtrl("label4");
label4_cstr = view.getCtrlStruct("label4");
label3 = (System.Windows.Forms.Label) view.getCtrl("label3");
label3_cstr = view.getCtrlStruct("label3");
label2 = (System.Windows.Forms.Label) view.getCtrl("label2");
label2_cstr = view.getCtrlStruct("label2");
label1 = (System.Windows.Forms.Label) view.getCtrl("label1");
label1_cstr = view.getCtrlStruct("label1");
 }}

}

