using System; 
using TControls; 
using Newtonsoft.Json.Linq;

namespace TLogic.ARQODE_UI.GestorProcesos
 { 
public class CVentanaProcesos
 { 
public static String _JSON { get { return "ew0KICAiJHNjaGVtYSI6ICIuLlxcU2NoZW1hc1xcU2NoZW1hX2Jhc2VfY29udHJvbC5qc29uIiwNCiAgImRlc2NyaXB0aW9uIjogIiIsDQogICJWYXJpYWJsZXMiOiBbXSwNCiAgIkNvbnRyb2xzIjogWw0KICAgIHsNCiAgICAgICJHdWlkIjogIlZlbnRhbmFQcm9jZXNvcyIsDQogICAgICAiQ2xhc3NfUGF0aCI6ICJBUlFPREVfVklTVUFMX0VESVRPUi5BUlFPREVfVUkuVmVudGFuYVByb2Nlc29zIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlVzZXJDb250cm9sIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiMS4wLjAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNzkyLA0KICAgICAgICAgICJIZWlnaHQiOiA1NTQNCiAgICAgICAgfSwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfQ0KICAgICAgfSwNCiAgICAgICJDb250cm9scyI6IFsNCiAgICAgICAgInRhYlByb2Nlc29zIiwNCiAgICAgICAgIlBMZWZ0Ig0KICAgICAgXQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAidGFiUHJvY2Vzb3MiLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuVGFiQ29udHJvbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJEb2NrIjogIkZpbGwiLA0KICAgICAgICAiVGFiSW5kZXgiOiAyLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkNvbnRyb2xzIjogWw0KICAgICAgICAiUGNvbnRlbnQiLA0KICAgICAgICAiUFByb2Nlc3NQYW5lbCINCiAgICAgIF0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlBjb250ZW50IiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlRhYlBhZ2UiLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiAzODQsDQogICAgICAgICAgIkhlaWdodCI6IDUyOA0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiA0LA0KICAgICAgICAgICJZIjogMjINCiAgICAgICAgfSwNCiAgICAgICAgIlRleHQiOiAiQmFzZSBwcm9jZXNzIiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIkF1dG9TY3JvbGxNaW5TaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDAsDQogICAgICAgICAgIkhlaWdodCI6IDANCiAgICAgICAgfSwNCiAgICAgICAgIlZlcnRpY2FsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9LA0KICAgICAgICAiSG9yaXpvbnRhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfQ0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiUFByb2Nlc3NQYW5lbCIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5UYWJQYWdlIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjE1OTAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMzg0LA0KICAgICAgICAgICJIZWlnaHQiOiA1MjgNCiAgICAgICAgfSwNCiAgICAgICAgIkxvY2F0aW9uIjogew0KICAgICAgICAgICJYIjogNCwNCiAgICAgICAgICAiWSI6IDIyDQogICAgICAgIH0sDQogICAgICAgICJUYWJJbmRleCI6IDEsDQogICAgICAgICJUZXh0IjogIlByb2Nlc3MiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9LA0KICAgICAgICAiQXV0b1Njcm9sbE1pblNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMCwNCiAgICAgICAgICAiSGVpZ2h0IjogMA0KICAgICAgICB9LA0KICAgICAgICAiVmVydGljYWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0sDQogICAgICAgICJIb3Jpem9udGFsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9DQogICAgICB9DQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJQTGVmdCIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5QYW5lbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDQwMCwNCiAgICAgICAgICAiSGVpZ2h0IjogNTU0DQogICAgICAgIH0sDQogICAgICAgICJEb2NrIjogIkxlZnQiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9LA0KICAgICAgICAiQXV0b1Njcm9sbE1pblNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMCwNCiAgICAgICAgICAiSGVpZ2h0IjogMA0KICAgICAgICB9LA0KICAgICAgICAiVmVydGljYWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0sDQogICAgICAgICJIb3Jpem9udGFsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkNvbnRyb2xzIjogWw0KICAgICAgICAiUFByb2Nlc3NMaXN0IiwNCiAgICAgICAgIlBQcm9jZXNzRGlyIg0KICAgICAgXQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiUFByb2Nlc3NMaXN0IiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlBhbmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjE1OTAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIkRvY2siOiAiRmlsbCIsDQogICAgICAgICJUYWJJbmRleCI6IDEsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0sDQogICAgICAgICJBdXRvU2Nyb2xsTWluU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiAwLA0KICAgICAgICAgICJIZWlnaHQiOiAwDQogICAgICAgIH0sDQogICAgICAgICJWZXJ0aWNhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfSwNCiAgICAgICAgIkhvcml6b250YWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0NCiAgICAgIH0sDQogICAgICAiQ29udHJvbHMiOiBbDQogICAgICAgICJMUHJvY2VzcyINCiAgICAgIF0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIkxQcm9jZXNzIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkxpc3RCb3giLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiRG9jayI6ICJGaWxsIiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfQ0KICAgICAgfSwNCiAgICAgICJFdmVudHMiOiB7DQogICAgICAgICJTZWxlY3RlZEluZGV4Q2hhbmdlZCI6ICJHZXN0acOzbiBkZSBQcm9jZXNvcy5DYXJnYXIgZGF0b3MgZGUgcHJvY2VzbyINCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogImNvbnRleHRNZW51X1Byb2Nlc28iLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuQ29udGV4dE1lbnVTdHJpcCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDExMSwNCiAgICAgICAgICAiSGVpZ2h0IjogMTM2DQogICAgICAgIH0sDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAyLA0KICAgICAgICAgICJSaWdodCI6IDEsDQogICAgICAgICAgIkJvdHRvbSI6IDIsDQogICAgICAgICAgIkxlZnQiOiAzMw0KICAgICAgICB9LA0KICAgICAgICAiTWVudSBpdGVtcyI6IFsNCiAgICAgICAgICB7DQogICAgICAgICAgICAiTmFtZSI6ICJOdWV2byIsDQogICAgICAgICAgICAiU2hvcnRjdXRLZXlzIjogIkN0cmwrTiIsDQogICAgICAgICAgICAiUHJvZ3JhbSI6ICJHZXN0acOzbiBkZSBQcm9jZXNvcy5Qcm9jZXNvLk51ZXZvIHByb2Nlc28iDQogICAgICAgICAgfSwNCiAgICAgICAgICB7DQogICAgICAgICAgICAiTmFtZSI6ICJDb3J0YXIiLA0KICAgICAgICAgICAgIlNob3J0Y3V0S2V5cyI6ICJDdHJsK1giLA0KICAgICAgICAgICAgIlByb2dyYW0iOiAiR2VzdGnDs24gZGUgUHJvY2Vzb3MuUHJvY2Vzby5Db3J0YXIiDQogICAgICAgICAgfSwNCiAgICAgICAgICB7DQogICAgICAgICAgICAiTmFtZSI6ICJQZWdhciIsDQogICAgICAgICAgICAiU2hvcnRjdXRLZXlzIjogIkN0cmwrViIsDQogICAgICAgICAgICAiUHJvZ3JhbSI6ICJHZXN0acOzbiBkZSBQcm9jZXNvcy5Qcm9jZXNvLlBlZ2FyIg0KICAgICAgICAgIH0sDQogICAgICAgICAgew0KICAgICAgICAgICAgIk5hbWUiOiAiRWxpbWluYXIiLA0KICAgICAgICAgICAgIlNob3J0Y3V0S2V5cyI6ICJOb25lIiwNCiAgICAgICAgICAgICJQcm9ncmFtIjogIkdlc3Rpw7NuIGRlIFByb2Nlc29zLlByb2Nlc28uRWxpbWluYXIgcHJvY2VzbyINCiAgICAgICAgICB9LA0KICAgICAgICAgIHsNCiAgICAgICAgICAgICJOYW1lIjogIkFzaWduYXIgYWwgcHJvZ3JhbWEgYWN0aXZvIiwNCiAgICAgICAgICAgICJTaG9ydGN1dEtleXMiOiAiQ3RybCtBIiwNCiAgICAgICAgICAgICJQcm9ncmFtIjogIkdlc3Rpw7NuIGRlIFByb2Nlc29zLlByb2Nlc28uQXNpZ25hciBwcm9jZXNvIg0KICAgICAgICAgIH0sDQogICAgICAgICAgew0KICAgICAgICAgICAgIk5hbWUiOiAiQnVzY2FyIHJlZmVyZW5jaWFzIiwNCiAgICAgICAgICAgICJTaG9ydGN1dEtleXMiOiAiQ3RybCtCIiwNCiAgICAgICAgICAgICJQcm9ncmFtIjogIkdlc3Rpw7NuIGRlIHByb2Nlc29zLkJ1c2NhciByZWZlcmVuY2lhcyBhIHByb2Nlc28gZW4gcHJvZ3JhbWFzIg0KICAgICAgICAgIH0NCiAgICAgICAgXQ0KICAgICAgfSwNCiAgICAgICJFdmVudHMiOiB7DQogICAgICAgICJ0b29sU3RyaXBNZW51SXRlbTEiOiAiR2VzdGnDs24gZGUgUHJvY2Vzb3MuUHJvY2Vzby5OdWV2byBwcm9jZXNvIiwNCiAgICAgICAgImNvcnRhclRvb2xTdHJpcE1lbnVJdGVtMSI6ICJHZXN0acOzbiBkZSBQcm9jZXNvcy5Qcm9jZXNvLkNvcnRhciIsDQogICAgICAgICJwZWdhclRvb2xTdHJpcE1lbnVJdGVtMSI6ICJHZXN0acOzbiBkZSBQcm9jZXNvcy5Qcm9jZXNvLlBlZ2FyIiwNCiAgICAgICAgImVsaW1pbmFyVG9vbFN0cmlwTWVudUl0ZW0xIjogIkdlc3Rpw7NuIGRlIFByb2Nlc29zLlByb2Nlc28uRWxpbWluYXIgcHJvY2VzbyIsDQogICAgICAgICJhc2lnbmFyQWxQcm9ncmFtYUFjdGl2b1Rvb2xTdHJpcE1lbnVJdGVtIjogIkdlc3Rpw7NuIGRlIFByb2Nlc29zLlByb2Nlc28uQXNpZ25hciBwcm9jZXNvIiwNCiAgICAgICAgImJ1c2NhclJlZmVyZW5jaWFzVG9vbFN0cmlwTWVudUl0ZW0iOiAiR2VzdGnDs24gZGUgcHJvY2Vzb3MuUHJvY2Vzby5CdXNjYXIgcmVmZXJlbmNpYXMgYSBwcm9jZXNvIGVuIHByb2dyYW1hcyINCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlBQcm9jZXNzRGlyIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlBhbmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjE1OTAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNDAwLA0KICAgICAgICAgICJIZWlnaHQiOiAzMDANCiAgICAgICAgfSwNCiAgICAgICAgIkRvY2siOiAiVG9wIiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIkF1dG9TY3JvbGxNaW5TaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDAsDQogICAgICAgICAgIkhlaWdodCI6IDANCiAgICAgICAgfSwNCiAgICAgICAgIlZlcnRpY2FsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9LA0KICAgICAgICAiSG9yaXpvbnRhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfQ0KICAgICAgfSwNCiAgICAgICJDb250cm9scyI6IFsNCiAgICAgICAgIlRWX1Byb2Nlc3NlcyINCiAgICAgIF0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlRWX1Byb2Nlc3NlcyIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5UcmVlVmlldyIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJEb2NrIjogIkZpbGwiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkV2ZW50cyI6IHsNCiAgICAgICAgIkFmdGVyU2VsZWN0IjogIkdlc3Rpw7NuIGRlIHByb2Nlc29zLkNhcmdhciBzdWJwcm9jZXNvcyINCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogImNvbnRleHRNZW51X1Byb2Nlc29zIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkNvbnRleHRNZW51U3RyaXAiLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiAxMTEsDQogICAgICAgICAgIkhlaWdodCI6IDEzNg0KICAgICAgICB9LA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMiwNCiAgICAgICAgICAiUmlnaHQiOiAxLA0KICAgICAgICAgICJCb3R0b20iOiAyLA0KICAgICAgICAgICJMZWZ0IjogMzMNCiAgICAgICAgfSwNCiAgICAgICAgIk1lbnUgaXRlbXMiOiBbDQogICAgICAgICAgew0KICAgICAgICAgICAgIk5hbWUiOiAiTnVldm8iLA0KICAgICAgICAgICAgIlNob3J0Y3V0S2V5cyI6ICJDdHJsK04iLA0KICAgICAgICAgICAgIlByb2dyYW0iOiAiR2VzdGnDs24gZGUgUHJvY2Vzb3MuR2VzdGnDs24uQWJyaXIgZmljaGEgZGUgcHJvY2VzbyINCiAgICAgICAgICB9LA0KICAgICAgICAgIHsNCiAgICAgICAgICAgICJOYW1lIjogIkNvcnRhciIsDQogICAgICAgICAgICAiU2hvcnRjdXRLZXlzIjogIkN0cmwrWCIsDQogICAgICAgICAgICAiUHJvZ3JhbSI6ICJHZXN0acOzbiBkZSBQcm9jZXNvcy5HZXN0acOzbi5Db3J0YXIiDQogICAgICAgICAgfSwNCiAgICAgICAgICB7DQogICAgICAgICAgICAiTmFtZSI6ICJQZWdhciIsDQogICAgICAgICAgICAiU2hvcnRjdXRLZXlzIjogIkN0cmwrViIsDQogICAgICAgICAgICAiUHJvZ3JhbSI6ICJHZXN0acOzbiBkZSBQcm9jZXNvcy5HZXN0acOzbi5QZWdhciINCiAgICAgICAgICB9LA0KICAgICAgICAgIHsNCiAgICAgICAgICAgICJOYW1lIjogIkVsaW1pbmFyIiwNCiAgICAgICAgICAgICJTaG9ydGN1dEtleXMiOiAiQ3RybCtEIiwNCiAgICAgICAgICAgICJQcm9ncmFtIjogIkdlc3Rpw7NuIGRlIFByb2Nlc29zLkdlc3Rpw7NuLkVsaW1pbmFyIGZpY2hlcm8gcHJvY2Vzb3MiDQogICAgICAgICAgfSwNCiAgICAgICAgICB7DQogICAgICAgICAgICAiTmFtZSI6ICJOdWV2YSBjYXJwZXRhIiwNCiAgICAgICAgICAgICJTaG9ydGN1dEtleXMiOiAiQ3RybCtQIiwNCiAgICAgICAgICAgICJQcm9ncmFtIjogIkdlc3Rpw7NuIGRlIFByb2Nlc29zLkdlc3Rpw7NuLk51ZXZhIGNhcnBldGEiDQogICAgICAgICAgfSwNCiAgICAgICAgICB7DQogICAgICAgICAgICAiTmFtZSI6ICJSZW5vbWJyYXIiLA0KICAgICAgICAgICAgIlNob3J0Y3V0S2V5cyI6ICJGMiIsDQogICAgICAgICAgICAiUHJvZ3JhbSI6ICJHZXN0acOzbiBkZSBQcm9jZXNvcy5HZXN0acOzbi5SZW5vbWJyYXIgZmljaGVybyBkZSBwcm9jZXNvIg0KICAgICAgICAgIH0NCiAgICAgICAgXQ0KICAgICAgfSwNCiAgICAgICJFdmVudHMiOiB7DQogICAgICAgICJOdWV2b0ZpY2hlcm9fVG9vbFN0cmlwTWVudUl0ZW0iOiAiR2VzdGnDs24gZGUgUHJvY2Vzb3MuR2VzdGnDs24uQWJyaXIgZmljaGEgZGUgcHJvY2VzbyIsDQogICAgICAgICJjb3J0YXJUb29sU3RyaXBNZW51SXRlbSI6ICJHZXN0acOzbiBkZSBQcm9jZXNvcy5HZXN0acOzbi5Db3J0YXIiLA0KICAgICAgICAicGVnYXJUb29sU3RyaXBNZW51SXRlbSI6ICJHZXN0acOzbiBkZSBQcm9jZXNvcy5HZXN0acOzbi5QZWdhciIsDQogICAgICAgICJlbGltaW5hclRvb2xTdHJpcE1lbnVJdGVtIjogIkdlc3Rpw7NuIGRlIFByb2Nlc29zLkdlc3Rpw7NuLkVsaW1pbmFyIGZpY2hlcm8gcHJvY2Vzb3MiLA0KICAgICAgICAibnVldmFDYXJwZXRhVG9vbFN0cmlwTWVudUl0ZW0iOiAiR2VzdGnDs24gZGUgUHJvY2Vzb3MuR2VzdGnDs24uTnVldmEgY2FycGV0YSIsDQogICAgICAgICJyZW5vbWJyYXJUb29sU3RyaXBNZW51SXRlbSI6ICJHZXN0acOzbiBkZSBQcm9jZXNvcy5HZXN0acOzbi5SZW5vbWJyYXIgZmljaGVybyBkZSBwcm9jZXNvIg0KICAgICAgfQ0KICAgIH0NCiAgXQ0KfQ=="; } }
public JObject MappedView { get { return JObject.Parse(System.Text.UTF8Encoding.UTF8.GetString(Convert.FromBase64String(_JSON))); } } 
public System.Windows.Forms.UserControl VentanaProcesos;
public CView.CtrlStruct VentanaProcesos_cstr;
public object VentanaProcesos_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("GestorProcesos.VentanaProcesos")[var] = value; 
	return (object)view.CtrlVars("GestorProcesos.VentanaProcesos")[var];
}
public System.Windows.Forms.TabControl tabProcesos;
public CView.CtrlStruct tabProcesos_cstr;
public object tabProcesos_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("tabProcesos")[var] = value; 
	return (object)view.CtrlVars("tabProcesos")[var];
}
public System.Windows.Forms.TabPage Pcontent;
public CView.CtrlStruct Pcontent_cstr;
public object Pcontent_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("Pcontent")[var] = value; 
	return (object)view.CtrlVars("Pcontent")[var];
}
public System.Windows.Forms.TabPage PProcessPanel;
public CView.CtrlStruct PProcessPanel_cstr;
public object PProcessPanel_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PProcessPanel")[var] = value; 
	return (object)view.CtrlVars("PProcessPanel")[var];
}
public System.Windows.Forms.Panel PLeft;
public CView.CtrlStruct PLeft_cstr;
public object PLeft_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PLeft")[var] = value; 
	return (object)view.CtrlVars("PLeft")[var];
}
public System.Windows.Forms.Panel PProcessList;
public CView.CtrlStruct PProcessList_cstr;
public object PProcessList_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PProcessList")[var] = value; 
	return (object)view.CtrlVars("PProcessList")[var];
}
public System.Windows.Forms.ListBox LProcess;
public CView.CtrlStruct LProcess_cstr;
public object LProcess_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("LProcess")[var] = value; 
	return (object)view.CtrlVars("LProcess")[var];
}
public System.Windows.Forms.ContextMenuStrip contextMenu_Proceso;
public CView.CtrlStruct contextMenu_Proceso_cstr;
public object contextMenu_Proceso_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("contextMenu_Proceso")[var] = value; 
	return (object)view.CtrlVars("contextMenu_Proceso")[var];
}
public System.Windows.Forms.Panel PProcessDir;
public CView.CtrlStruct PProcessDir_cstr;
public object PProcessDir_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PProcessDir")[var] = value; 
	return (object)view.CtrlVars("PProcessDir")[var];
}
public System.Windows.Forms.TreeView TV_Processes;
public CView.CtrlStruct TV_Processes_cstr;
public object TV_Processes_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("TV_Processes")[var] = value; 
	return (object)view.CtrlVars("TV_Processes")[var];
}
public System.Windows.Forms.ContextMenuStrip contextMenu_Procesos;
public CView.CtrlStruct contextMenu_Procesos_cstr;
public object contextMenu_Procesos_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("contextMenu_Procesos")[var] = value; 
	return (object)view.CtrlVars("contextMenu_Procesos")[var];
}
public CView view; 
public CVentanaProcesos (CViewsManager vm) { view = (vm.getFirstView("GestorProcesos.VentanaProcesos") != null)? vm.getFirstView("GestorProcesos.VentanaProcesos"): vm.AddView("GestorProcesos.VentanaProcesos");
VentanaProcesos = (System.Windows.Forms.UserControl) view.getCtrl("GestorProcesos.VentanaProcesos");
VentanaProcesos_cstr = view.getCtrlStruct("GestorProcesos.VentanaProcesos");
tabProcesos = (System.Windows.Forms.TabControl) view.getCtrl("tabProcesos");
tabProcesos_cstr = view.getCtrlStruct("tabProcesos");
Pcontent = (System.Windows.Forms.TabPage) view.getCtrl("Pcontent");
Pcontent_cstr = view.getCtrlStruct("Pcontent");
PProcessPanel = (System.Windows.Forms.TabPage) view.getCtrl("PProcessPanel");
PProcessPanel_cstr = view.getCtrlStruct("PProcessPanel");
PLeft = (System.Windows.Forms.Panel) view.getCtrl("PLeft");
PLeft_cstr = view.getCtrlStruct("PLeft");
PProcessList = (System.Windows.Forms.Panel) view.getCtrl("PProcessList");
PProcessList_cstr = view.getCtrlStruct("PProcessList");
LProcess = (System.Windows.Forms.ListBox) view.getCtrl("LProcess");
LProcess_cstr = view.getCtrlStruct("LProcess");
contextMenu_Proceso = (System.Windows.Forms.ContextMenuStrip) view.getCtrl("contextMenu_Proceso");
contextMenu_Proceso_cstr = view.getCtrlStruct("contextMenu_Proceso");
PProcessDir = (System.Windows.Forms.Panel) view.getCtrl("PProcessDir");
PProcessDir_cstr = view.getCtrlStruct("PProcessDir");
TV_Processes = (System.Windows.Forms.TreeView) view.getCtrl("TV_Processes");
TV_Processes_cstr = view.getCtrlStruct("TV_Processes");
contextMenu_Procesos = (System.Windows.Forms.ContextMenuStrip) view.getCtrl("contextMenu_Procesos");
contextMenu_Procesos_cstr = view.getCtrlStruct("contextMenu_Procesos");
 }}

}

