using System; 
using TControls; 
using Newtonsoft.Json.Linq;

namespace TLogic.ARQODE_UI.GestorControles
 { 
public class CFormControlesEventos
 { 
public static String _JSON { get { return "ew0KICAiJHNjaGVtYSI6ICIuLlxcU2NoZW1hc1xcU2NoZW1hX2Jhc2VfY29udHJvbC5qc29uIiwNCiAgImRlc2NyaXB0aW9uIjogIiIsDQogICJWYXJpYWJsZXMiOiBbDQogICAgIkxpc3RhIGRlIGV2ZW50b3MgYWN0aXZhIg0KICBdLA0KICAiQ29udHJvbHMiOiBbDQogICAgew0KICAgICAgIkd1aWQiOiAiRm9ybUNvbnRyb2xlc0V2ZW50b3MiLA0KICAgICAgIkNsYXNzX1BhdGgiOiAiQVJRT0RFX1ZJU1VBTF9FRElUT1IuQVJRT0RFX1VJLkZvcm1Db250cm9sZXNFdmVudG9zIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkZvcm0iLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICIxLjAuMC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiA5NzMsDQogICAgICAgICAgIkhlaWdodCI6IDc5NQ0KICAgICAgICB9LA0KICAgICAgICAiVGV4dCI6ICJDb250cm9scyBldmVudHMiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkNvbnRyb2xzIjogWw0KICAgICAgICAiUFJpZ2h0IiwNCiAgICAgICAgIlBMZWZ0Ig0KICAgICAgXSwNCiAgICAgICJFdmVudHMiOiB7DQogICAgICAgICJGb3JtQ2xvc2VkIjogIkdlc3Rpw7NuIGRlIGNvbnRyb2xlcy5DZXJyYXIgdmVudGFuYSINCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlBSaWdodCIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5QYW5lbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDY1NSwNCiAgICAgICAgICAiSGVpZ2h0IjogNzU3DQogICAgICAgIH0sDQogICAgICAgICJMb2NhdGlvbiI6IHsNCiAgICAgICAgICAiWCI6IDMwMiwNCiAgICAgICAgICAiWSI6IDANCiAgICAgICAgfSwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIkF1dG9TY3JvbGxNaW5TaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDAsDQogICAgICAgICAgIkhlaWdodCI6IDANCiAgICAgICAgfSwNCiAgICAgICAgIlZlcnRpY2FsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9LA0KICAgICAgICAiSG9yaXpvbnRhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfQ0KICAgICAgfSwNCiAgICAgICJDb250cm9scyI6IFsNCiAgICAgICAgIlBFdmVudEJvdHRvbSIsDQogICAgICAgICJQVG9wRXZlbnRfQ29uc3VsdCINCiAgICAgIF0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlBFdmVudEJvdHRvbSIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5QYW5lbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDY1NSwNCiAgICAgICAgICAiSGVpZ2h0IjogMzUyDQogICAgICAgIH0sDQogICAgICAgICJEb2NrIjogIkJvdHRvbSIsDQogICAgICAgICJUYWJJbmRleCI6IDMsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0sDQogICAgICAgICJBdXRvU2Nyb2xsTWluU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiAwLA0KICAgICAgICAgICJIZWlnaHQiOiAwDQogICAgICAgIH0sDQogICAgICAgICJWZXJ0aWNhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfSwNCiAgICAgICAgIkhvcml6b250YWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0NCiAgICAgIH0sDQogICAgICAiQ29udHJvbHMiOiBbDQogICAgICAgICJQRXZlbnRzR3JpZCIsDQogICAgICAgICJwYW5lbDEiDQogICAgICBdDQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJQRXZlbnRzR3JpZCIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5QYW5lbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJEb2NrIjogIkZpbGwiLA0KICAgICAgICAiVGFiSW5kZXgiOiAyLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9LA0KICAgICAgICAiQXV0b1Njcm9sbE1pblNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMCwNCiAgICAgICAgICAiSGVpZ2h0IjogMA0KICAgICAgICB9LA0KICAgICAgICAiVmVydGljYWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0sDQogICAgICAgICJIb3Jpem9udGFsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkNvbnRyb2xzIjogWw0KICAgICAgICAiREdfRXZlbnRvc0NvbnRyb2wiDQogICAgICBdDQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJER19FdmVudG9zQ29udHJvbCIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5EYXRhR3JpZFZpZXciLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiA2NDksDQogICAgICAgICAgIkhlaWdodCI6IDI5MQ0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiAzLA0KICAgICAgICAgICJZIjogMw0KICAgICAgICB9LA0KICAgICAgICAiVGFiSW5kZXgiOiAxLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9LA0KICAgICAgICAiRWRpdE1vZGUiOiAiRWRpdE9uS2V5c3Ryb2tlT3JGMiIsDQogICAgICAgICJTZWxlY3Rpb25Nb2RlIjogIkNlbGxTZWxlY3QiLA0KICAgICAgICAiU2Nyb2xsQmFycyI6ICJCb3RoIiwNCiAgICAgICAgIkFsbG93VXNlclRvQWRkUm93cyI6IHRydWUsDQogICAgICAgICJBbGxvd1VzZXJUb0RlbGV0ZVJvd3MiOiB0cnVlLA0KICAgICAgICAiQWxsb3dVc2VyVG9PcmRlckNvbHVtbnMiOiBmYWxzZSwNCiAgICAgICAgIkFsbG93VXNlclRvUmVzaXplQ29sdW1ucyI6IHRydWUsDQogICAgICAgICJBbGxvd1VzZXJUb1Jlc2l6ZVJvd3MiOiBmYWxzZSwNCiAgICAgICAgIkF1dG9TaXplQ29sdW1uc01vZGUiOiAiRmlsbCIsDQogICAgICAgICJNdWx0aVNlbGVjdCI6IGZhbHNlLA0KICAgICAgICAiQ29sdW1uSGVhZGVyc0hlaWdodFNpemVNb2RlIjogIkF1dG9TaXplIiwNCiAgICAgICAgIlJvd0hlYWRlcnNXaWR0aFNpemVNb2RlIjogIkVuYWJsZVJlc2l6aW5nIiwNCiAgICAgICAgIkFsdGVybmF0aW5nUm93c0RlZmF1bHRDZWxsU3R5bGUiOiB7fQ0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAicGFuZWwxIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlBhbmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjE1OTAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNjU1LA0KICAgICAgICAgICJIZWlnaHQiOiA1OA0KICAgICAgICB9LA0KICAgICAgICAiRG9jayI6ICJCb3R0b20iLA0KICAgICAgICAiVGFiSW5kZXgiOiAxLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9LA0KICAgICAgICAiQXV0b1Njcm9sbE1pblNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMCwNCiAgICAgICAgICAiSGVpZ2h0IjogMA0KICAgICAgICB9LA0KICAgICAgICAiVmVydGljYWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0sDQogICAgICAgICJIb3Jpem9udGFsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkNvbnRyb2xzIjogWw0KICAgICAgICAiQkd1YXJkYXIiDQogICAgICBdDQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJCR3VhcmRhciIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5CdXR0b24iLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiA5MSwNCiAgICAgICAgICAiSGVpZ2h0IjogMzANCiAgICAgICAgfSwNCiAgICAgICAgIkxvY2F0aW9uIjogew0KICAgICAgICAgICJYIjogNTUyLA0KICAgICAgICAgICJZIjogMTQNCiAgICAgICAgfSwNCiAgICAgICAgIlRleHQiOiAiU2F2ZSIsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0NCiAgICAgIH0sDQogICAgICAiRXZlbnRzIjogew0KICAgICAgICAiQ2xpY2siOiAiR2VzdGnDs24gZGUgY29udHJvbGVzLkd1YXJkYXIgZXZlbnRvcyBlbiBjb250cm9sIg0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiUFRvcEV2ZW50X0NvbnN1bHQiLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuUGFuZWwiLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiRG9jayI6ICJGaWxsIiwNCiAgICAgICAgIlRhYkluZGV4IjogMiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIkF1dG9TY3JvbGxNaW5TaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDAsDQogICAgICAgICAgIkhlaWdodCI6IDANCiAgICAgICAgfSwNCiAgICAgICAgIlZlcnRpY2FsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9LA0KICAgICAgICAiSG9yaXpvbnRhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfQ0KICAgICAgfSwNCiAgICAgICJDb250cm9scyI6IFsNCiAgICAgICAgInRvb2xTdHJpcDEiLA0KICAgICAgICAiTGlzdGFFdmVudG9zIg0KICAgICAgXQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAidG9vbFN0cmlwMSIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5Ub29sU3RyaXAiLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiA2NTUsDQogICAgICAgICAgIkhlaWdodCI6IDI1DQogICAgICAgIH0sDQogICAgICAgICJEb2NrIjogIlRvcCIsDQogICAgICAgICJUYWJJbmRleCI6IDEsDQogICAgICAgICJUZXh0IjogInRvb2xTdHJpcDEiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMCwNCiAgICAgICAgICAiUmlnaHQiOiAxLA0KICAgICAgICAgICJCb3R0b20iOiAwLA0KICAgICAgICAgICJMZWZ0IjogMA0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkV2ZW50cyI6IHt9DQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJMaXN0YUV2ZW50b3MiLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuTGlzdFZpZXciLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiA2NTIsDQogICAgICAgICAgIkhlaWdodCI6IDM0OA0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiAwLA0KICAgICAgICAgICJZIjogNTENCiAgICAgICAgfSwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfQ0KICAgICAgfSwNCiAgICAgICJFdmVudHMiOiB7DQogICAgICAgICJTZWxlY3RlZEluZGV4Q2hhbmdlZCI6ICJHZXN0acOzbiBkZSBjb250cm9sZXMuU2VsZWNjaW9uYXIgZXZlbnRvIg0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiUExlZnQiLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuUGFuZWwiLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiRG9jayI6ICJGaWxsIiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIkF1dG9TY3JvbGxNaW5TaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDAsDQogICAgICAgICAgIkhlaWdodCI6IDANCiAgICAgICAgfSwNCiAgICAgICAgIlZlcnRpY2FsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9LA0KICAgICAgICAiSG9yaXpvbnRhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfQ0KICAgICAgfSwNCiAgICAgICJDb250cm9scyI6IFsNCiAgICAgICAgIlRWX0NvbnRyb2xlcyINCiAgICAgIF0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlRWX0NvbnRyb2xlcyIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5UcmVlVmlldyIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJEb2NrIjogIkZpbGwiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkV2ZW50cyI6IHsNCiAgICAgICAgIkFmdGVyU2VsZWN0IjogIkdlc3Rpw7NuIGRlIGNvbnRyb2xlcy5DYXJnYXIgZXZlbnRvcyINCiAgICAgIH0NCiAgICB9DQogIF0NCn0="; } }
public JObject MappedView { get { return JObject.Parse(System.Text.UTF8Encoding.UTF8.GetString(Convert.FromBase64String(_JSON))); } } 
public System.Windows.Forms.Form FormControlesEventos;
public CView.CtrlStruct FormControlesEventos_cstr;
public object FormControlesEventos_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("GestorControles.FormControlesEventos")[var] = value; 
	return (object)view.CtrlVars("GestorControles.FormControlesEventos")[var];
}
public System.Windows.Forms.Panel PRight;
public CView.CtrlStruct PRight_cstr;
public object PRight_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PRight")[var] = value; 
	return (object)view.CtrlVars("PRight")[var];
}
public System.Windows.Forms.Panel PEventBottom;
public CView.CtrlStruct PEventBottom_cstr;
public object PEventBottom_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PEventBottom")[var] = value; 
	return (object)view.CtrlVars("PEventBottom")[var];
}
public System.Windows.Forms.Panel PEventsGrid;
public CView.CtrlStruct PEventsGrid_cstr;
public object PEventsGrid_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PEventsGrid")[var] = value; 
	return (object)view.CtrlVars("PEventsGrid")[var];
}
public System.Windows.Forms.DataGridView DG_EventosControl;
public CView.CtrlStruct DG_EventosControl_cstr;
public object DG_EventosControl_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("DG_EventosControl")[var] = value; 
	return (object)view.CtrlVars("DG_EventosControl")[var];
}
public System.Windows.Forms.Panel panel1;
public CView.CtrlStruct panel1_cstr;
public object panel1_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("panel1")[var] = value; 
	return (object)view.CtrlVars("panel1")[var];
}
public System.Windows.Forms.Button BGuardar;
public CView.CtrlStruct BGuardar_cstr;
public object BGuardar_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("BGuardar")[var] = value; 
	return (object)view.CtrlVars("BGuardar")[var];
}
public System.Windows.Forms.Panel PTopEvent_Consult;
public CView.CtrlStruct PTopEvent_Consult_cstr;
public object PTopEvent_Consult_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PTopEvent_Consult")[var] = value; 
	return (object)view.CtrlVars("PTopEvent_Consult")[var];
}
public System.Windows.Forms.ToolStrip toolStrip1;
public CView.CtrlStruct toolStrip1_cstr;
public object toolStrip1_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("toolStrip1")[var] = value; 
	return (object)view.CtrlVars("toolStrip1")[var];
}
public System.Windows.Forms.ListView ListaEventos;
public CView.CtrlStruct ListaEventos_cstr;
public object ListaEventos_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("ListaEventos")[var] = value; 
	return (object)view.CtrlVars("ListaEventos")[var];
}
public System.Windows.Forms.Panel PLeft;
public CView.CtrlStruct PLeft_cstr;
public object PLeft_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PLeft")[var] = value; 
	return (object)view.CtrlVars("PLeft")[var];
}
public System.Windows.Forms.TreeView TV_Controles;
public CView.CtrlStruct TV_Controles_cstr;
public object TV_Controles_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("TV_Controles")[var] = value; 
	return (object)view.CtrlVars("TV_Controles")[var];
}
public object Lista_de_eventos_activa { get { return (view.vars.ContainsKey("Lista de eventos activa"))? (object)view.vars["Lista de eventos activa"]: null; } set { view.vars["Lista de eventos activa"] = value; } }
public CView view; 
public CFormControlesEventos (CViewsManager vm) { view = (vm.getFirstView("GestorControles.FormControlesEventos") != null)? vm.getFirstView("GestorControles.FormControlesEventos"): vm.AddView("GestorControles.FormControlesEventos");
FormControlesEventos = (System.Windows.Forms.Form) view.getCtrl("GestorControles.FormControlesEventos");
FormControlesEventos_cstr = view.getCtrlStruct("GestorControles.FormControlesEventos");
PRight = (System.Windows.Forms.Panel) view.getCtrl("PRight");
PRight_cstr = view.getCtrlStruct("PRight");
PEventBottom = (System.Windows.Forms.Panel) view.getCtrl("PEventBottom");
PEventBottom_cstr = view.getCtrlStruct("PEventBottom");
PEventsGrid = (System.Windows.Forms.Panel) view.getCtrl("PEventsGrid");
PEventsGrid_cstr = view.getCtrlStruct("PEventsGrid");
DG_EventosControl = (System.Windows.Forms.DataGridView) view.getCtrl("DG_EventosControl");
DG_EventosControl_cstr = view.getCtrlStruct("DG_EventosControl");
panel1 = (System.Windows.Forms.Panel) view.getCtrl("panel1");
panel1_cstr = view.getCtrlStruct("panel1");
BGuardar = (System.Windows.Forms.Button) view.getCtrl("BGuardar");
BGuardar_cstr = view.getCtrlStruct("BGuardar");
PTopEvent_Consult = (System.Windows.Forms.Panel) view.getCtrl("PTopEvent_Consult");
PTopEvent_Consult_cstr = view.getCtrlStruct("PTopEvent_Consult");
toolStrip1 = (System.Windows.Forms.ToolStrip) view.getCtrl("toolStrip1");
toolStrip1_cstr = view.getCtrlStruct("toolStrip1");
ListaEventos = (System.Windows.Forms.ListView) view.getCtrl("ListaEventos");
ListaEventos_cstr = view.getCtrlStruct("ListaEventos");
PLeft = (System.Windows.Forms.Panel) view.getCtrl("PLeft");
PLeft_cstr = view.getCtrlStruct("PLeft");
TV_Controles = (System.Windows.Forms.TreeView) view.getCtrl("TV_Controles");
TV_Controles_cstr = view.getCtrlStruct("TV_Controles");
 }}

}

