using System; 
using TControls; 
using Newtonsoft.Json.Linq;

namespace TLogic.ARQODE_UI.ARQODE_UI
{ 
public class CVisorTexto
 { 
String _JSON = "ew0KICAiJHNjaGVtYSI6ICIuLlxcU2NoZW1hc1xcU2NoZW1hX2Jhc2VfY29udHJvbC5qc29uIiwNCiAgImRlc2NyaXB0aW9uIjogIiIsDQogICJWYXJpYWJsZXMiOiBbXSwNCiAgIkNvbnRyb2xzIjogWw0KICAgIHsNCiAgICAgICJHdWlkIjogIlZpc29yVGV4dG8iLA0KICAgICAgIkNsYXNzX1BhdGgiOiAiQVJRT0RFX1ZJU1VBTF9FRElUT1IuVkVOVEFOQVNfVVNPX0dFTkVSQUwuVmlzb3JUZXh0byIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5Gb3JtIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiMS4wLjAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogOTM5LA0KICAgICAgICAgICJIZWlnaHQiOiA1NjgNCiAgICAgICAgfSwNCiAgICAgICAgIlRleHQiOiAiVmlzb3IiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkNvbnRyb2xzIjogWw0KICAgICAgICAiUENvbnRlbnQiLA0KICAgICAgICAiUFRvcCINCiAgICAgIF0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlBDb250ZW50IiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlBhbmVsIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIkRvY2siOiAiRmlsbCIsDQogICAgICAgICJUYWJJbmRleCI6IDIsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0sDQogICAgICAgICJBdXRvU2Nyb2xsTWluU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiAwLA0KICAgICAgICAgICJIZWlnaHQiOiAwDQogICAgICAgIH0sDQogICAgICAgICJWZXJ0aWNhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfSwNCiAgICAgICAgIkhvcml6b250YWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0NCiAgICAgIH0sDQogICAgICAiQ29udHJvbHMiOiBbDQogICAgICAgICJSQl9UZXh0byINCiAgICAgIF0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlJCX1RleHRvIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLlJpY2hUZXh0Qm94IiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIkRvY2siOiAiRmlsbCIsDQogICAgICAgICJUYWJJbmRleCI6IDEsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0NCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlBUb3AiLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuUGFuZWwiLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTA4Ny4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiA5MjMsDQogICAgICAgICAgIkhlaWdodCI6IDQ5DQogICAgICAgIH0sDQogICAgICAgICJEb2NrIjogIlRvcCIsDQogICAgICAgICJUYWJJbmRleCI6IDEsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0sDQogICAgICAgICJBdXRvU2Nyb2xsTWluU2l6ZSI6IHsNCiAgICAgICAgICAiV2lkdGgiOiAwLA0KICAgICAgICAgICJIZWlnaHQiOiAwDQogICAgICAgIH0sDQogICAgICAgICJWZXJ0aWNhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfSwNCiAgICAgICAgIkhvcml6b250YWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0NCiAgICAgIH0sDQogICAgICAiQ29udHJvbHMiOiBbDQogICAgICAgICJMUmVzIiwNCiAgICAgICAgIkJCdXNjYXIiLA0KICAgICAgICAiQ0hfUGFsYWJyYSIsDQogICAgICAgICJDSF9DYXNlU2Vuc2l0aXZlIiwNCiAgICAgICAgIlRCX0J1c3F1ZWRhIg0KICAgICAgXQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiTFJlcyIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5MYWJlbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xMDg3LjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDAsDQogICAgICAgICAgIkhlaWdodCI6IDE2DQogICAgICAgIH0sDQogICAgICAgICJMb2NhdGlvbiI6IHsNCiAgICAgICAgICAiWCI6IDY2MSwNCiAgICAgICAgICAiWSI6IDE5DQogICAgICAgIH0sDQogICAgICAgICJUYWJJbmRleCI6IDMsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAwLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDAsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0sDQogICAgICAgICJUZXh0QWxpZ24iOiAiVG9wTGVmdCINCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIkJCdXNjYXIiLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuQnV0dG9uIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMTA1LA0KICAgICAgICAgICJIZWlnaHQiOiAzMA0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiA1NDAsDQogICAgICAgICAgIlkiOiAxMg0KICAgICAgICB9LA0KICAgICAgICAiVGFiSW5kZXgiOiAyLA0KICAgICAgICAiVGV4dCI6ICJCdXNjYXIiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9DQogICAgICB9DQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJDSF9QYWxhYnJhIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkNoZWNrQm94IiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMTQyLA0KICAgICAgICAgICJIZWlnaHQiOiAyMA0KICAgICAgICB9LA0KICAgICAgICAiTG9jYXRpb24iOiB7DQogICAgICAgICAgIlgiOiAzODQsDQogICAgICAgICAgIlkiOiAxNg0KICAgICAgICB9LA0KICAgICAgICAiVGFiSW5kZXgiOiAxLA0KICAgICAgICAiVGV4dCI6ICJQYWxhYnJhcyBjb21wbGV0YXMiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9DQogICAgICB9DQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJDSF9DYXNlU2Vuc2l0aXZlIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkNoZWNrQm94IiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjEwODcuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNDMsDQogICAgICAgICAgIkhlaWdodCI6IDIwDQogICAgICAgIH0sDQogICAgICAgICJMb2NhdGlvbiI6IHsNCiAgICAgICAgICAiWCI6IDMzNSwNCiAgICAgICAgICAiWSI6IDE1DQogICAgICAgIH0sDQogICAgICAgICJUYWJJbmRleCI6IDEsDQogICAgICAgICJUZXh0IjogIkFhIiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfQ0KICAgICAgfQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiVEJfQnVzcXVlZGEiLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuVGV4dEJveCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xMDg3LjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDMxNiwNCiAgICAgICAgICAiSGVpZ2h0IjogMjINCiAgICAgICAgfSwNCiAgICAgICAgIkxvY2F0aW9uIjogew0KICAgICAgICAgICJYIjogMTMsDQogICAgICAgICAgIlkiOiAxMw0KICAgICAgICB9LA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9DQogICAgICB9DQogICAgfQ0KICBdDQp9";
public JObject MappedView { get { return JObject.Parse(System.Text.UTF8Encoding.UTF8.GetString(Convert.FromBase64String(_JSON))); } } 
public System.Windows.Forms.Form VisorTexto;
public CView.CtrlStruct VisorTexto_cstr;
public object VisorTexto_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("ARQODE_UI.VisorTexto")[var] = value; 
	return (object)view.CtrlVars("ARQODE_UI.VisorTexto")[var];
}
public System.Windows.Forms.Panel PContent;
public CView.CtrlStruct PContent_cstr;
public object PContent_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PContent")[var] = value; 
	return (object)view.CtrlVars("PContent")[var];
}
public System.Windows.Forms.RichTextBox RB_Texto;
public CView.CtrlStruct RB_Texto_cstr;
public object RB_Texto_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("RB_Texto")[var] = value; 
	return (object)view.CtrlVars("RB_Texto")[var];
}
public System.Windows.Forms.Panel PTop;
public CView.CtrlStruct PTop_cstr;
public object PTop_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PTop")[var] = value; 
	return (object)view.CtrlVars("PTop")[var];
}
public System.Windows.Forms.Label LRes;
public CView.CtrlStruct LRes_cstr;
public object LRes_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("LRes")[var] = value; 
	return (object)view.CtrlVars("LRes")[var];
}
public System.Windows.Forms.Button BBuscar;
public CView.CtrlStruct BBuscar_cstr;
public object BBuscar_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("BBuscar")[var] = value; 
	return (object)view.CtrlVars("BBuscar")[var];
}
public System.Windows.Forms.CheckBox CH_Palabra;
public CView.CtrlStruct CH_Palabra_cstr;
public object CH_Palabra_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("CH_Palabra")[var] = value; 
	return (object)view.CtrlVars("CH_Palabra")[var];
}
public System.Windows.Forms.CheckBox CH_CaseSensitive;
public CView.CtrlStruct CH_CaseSensitive_cstr;
public object CH_CaseSensitive_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("CH_CaseSensitive")[var] = value; 
	return (object)view.CtrlVars("CH_CaseSensitive")[var];
}
public System.Windows.Forms.TextBox TB_Busqueda;
public CView.CtrlStruct TB_Busqueda_cstr;
public object TB_Busqueda_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("TB_Busqueda")[var] = value; 
	return (object)view.CtrlVars("TB_Busqueda")[var];
}
public CView view; 
public CVisorTexto (CViewsManager vm) { view = (vm.getFirstView("ARQODE_UI.VisorTexto") != null)? vm.getFirstView("ARQODE_UI.VisorTexto"): vm.AddView("ARQODE_UI.VisorTexto");
VisorTexto = (System.Windows.Forms.Form) view.getCtrl("ARQODE_UI.VisorTexto");
VisorTexto_cstr = view.getCtrlStruct("ARQODE_UI.VisorTexto");
PContent = (System.Windows.Forms.Panel) view.getCtrl("PContent");
PContent_cstr = view.getCtrlStruct("PContent");
RB_Texto = (System.Windows.Forms.RichTextBox) view.getCtrl("RB_Texto");
RB_Texto_cstr = view.getCtrlStruct("RB_Texto");
PTop = (System.Windows.Forms.Panel) view.getCtrl("PTop");
PTop_cstr = view.getCtrlStruct("PTop");
LRes = (System.Windows.Forms.Label) view.getCtrl("LRes");
LRes_cstr = view.getCtrlStruct("LRes");
BBuscar = (System.Windows.Forms.Button) view.getCtrl("BBuscar");
BBuscar_cstr = view.getCtrlStruct("BBuscar");
CH_Palabra = (System.Windows.Forms.CheckBox) view.getCtrl("CH_Palabra");
CH_Palabra_cstr = view.getCtrlStruct("CH_Palabra");
CH_CaseSensitive = (System.Windows.Forms.CheckBox) view.getCtrl("CH_CaseSensitive");
CH_CaseSensitive_cstr = view.getCtrlStruct("CH_CaseSensitive");
TB_Busqueda = (System.Windows.Forms.TextBox) view.getCtrl("TB_Busqueda");
TB_Busqueda_cstr = view.getCtrlStruct("TB_Busqueda");
 }}

}

