using System; 
using TControls; 
using Newtonsoft.Json.Linq;

namespace TLogic.Views.VentanasUsoGeneral
 { 
public class CVentanaEdicion
 { 
public static String _JSON { get { return "ew0KICAiJHNjaGVtYSI6ICIuLlxcU2NoZW1hc1xcU2NoZW1hX2Jhc2VfY29udHJvbC5qc29uIiwNCiAgImRlc2NyaXB0aW9uIjogIiIsDQogICJWYXJpYWJsZXMiOiBbDQogICAgIkRhdGFTZXQiLA0KICAgICJEYXRhQWRhcHRlciIsDQogICAgIkRhdGFWaWV3IERhdG8gYWN0aXZvIg0KICBdLA0KICAiQ29udHJvbHMiOiBbDQogICAgew0KICAgICAgIkd1aWQiOiAiVmVudGFuYUVkaWNpb24iLA0KICAgICAgIkNsYXNzX1BhdGgiOiAiQVJRT0RFX1ZJU1VBTF9FRElUT1IuUkVHSVNUUk9fQUNDRVNPUy5WZW50YW5hRWRpY2lvbiIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5Gb3JtIiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiMS4wLjAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogODAyLA0KICAgICAgICAgICJIZWlnaHQiOiA1MTcNCiAgICAgICAgfSwNCiAgICAgICAgIlRleHQiOiAiRWRpY2nDs24gZGUgZGF0b3MiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkNvbnRyb2xzIjogWw0KICAgICAgICAiUENvbnRlbnQiDQogICAgICBdLA0KICAgICAgIkV2ZW50cyI6IHt9DQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJQQ29udGVudCIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5QYW5lbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJEb2NrIjogIkZpbGwiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9LA0KICAgICAgICAiQXV0b1Njcm9sbE1pblNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogMCwNCiAgICAgICAgICAiSGVpZ2h0IjogMA0KICAgICAgICB9LA0KICAgICAgICAiVmVydGljYWxTY3JvbGwiOiB7DQogICAgICAgICAgIkVuYWJsZWQiOiB0cnVlDQogICAgICAgIH0sDQogICAgICAgICJIb3Jpem9udGFsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkNvbnRyb2xzIjogWw0KICAgICAgICAiUFRvcCIsDQogICAgICAgICJQQ29udGVuaWRvIg0KICAgICAgXQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiUFRvcCIsDQogICAgICAiVHlwZSI6ICJTeXN0ZW0uV2luZG93cy5Gb3Jtcy5QYW5lbCIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDc4NiwNCiAgICAgICAgICAiSGVpZ2h0IjogNDYNCiAgICAgICAgfSwNCiAgICAgICAgIkRvY2siOiAiVG9wIiwNCiAgICAgICAgIlRhYkluZGV4IjogMiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIkF1dG9TY3JvbGxNaW5TaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDAsDQogICAgICAgICAgIkhlaWdodCI6IDANCiAgICAgICAgfSwNCiAgICAgICAgIlZlcnRpY2FsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9LA0KICAgICAgICAiSG9yaXpvbnRhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfQ0KICAgICAgfSwNCiAgICAgICJDb250cm9scyI6IFsNCiAgICAgICAgIkJOdWV2YUZpbGEiLA0KICAgICAgICAiQkd1YXJkYXIiDQogICAgICBdDQogICAgfSwNCiAgICB7DQogICAgICAiR3VpZCI6ICJCTnVldmFGaWxhIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkJ1dHRvbiIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDEzMSwNCiAgICAgICAgICAiSGVpZ2h0IjogMzMNCiAgICAgICAgfSwNCiAgICAgICAgIkxvY2F0aW9uIjogew0KICAgICAgICAgICJYIjogNjQzLA0KICAgICAgICAgICJZIjogNw0KICAgICAgICB9LA0KICAgICAgICAiVGV4dCI6ICJBw7FhZGlyIGZpbGEiLA0KICAgICAgICAiUGFkZGluZyI6IHsNCiAgICAgICAgICAiVG9wIjogMywNCiAgICAgICAgICAiUmlnaHQiOiAzLA0KICAgICAgICAgICJCb3R0b20iOiAzLA0KICAgICAgICAgICJMZWZ0IjogMw0KICAgICAgICB9DQogICAgICB9LA0KICAgICAgIkV2ZW50cyI6IHsNCiAgICAgICAgIkNsaWNrIjogIlZlbnRhbmEgZGUgZWRpY2nDs24uQcOxYWRpciBudWV2byByZWdpc3RybyINCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIkJHdWFyZGFyIiwNCiAgICAgICJUeXBlIjogIlN5c3RlbS5XaW5kb3dzLkZvcm1zLkJ1dHRvbiIsDQogICAgICAiRGVzY3JpcHRpb24iOiAiIiwNCiAgICAgICJWZXJzaW9uIjogIjQuNi4xNTkwLjAiLA0KICAgICAgIkNvbmZpZ3VyYXRpb24iOiB7DQogICAgICAgICJTaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDEzMSwNCiAgICAgICAgICAiSGVpZ2h0IjogMzMNCiAgICAgICAgfSwNCiAgICAgICAgIkxvY2F0aW9uIjogew0KICAgICAgICAgICJYIjogNTA2LA0KICAgICAgICAgICJZIjogNw0KICAgICAgICB9LA0KICAgICAgICAiVGV4dCI6ICJHdWFyZGFyIiwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfQ0KICAgICAgfSwNCiAgICAgICJFdmVudHMiOiB7DQogICAgICAgICJDbGljayI6ICJWZW50YW5hIGRlIGVkaWNpw7NuLkRhdG9zIGFjdHVhbGl6YWRvcyINCiAgICAgIH0NCiAgICB9LA0KICAgIHsNCiAgICAgICJHdWlkIjogIlBDb250ZW5pZG8iLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuUGFuZWwiLA0KICAgICAgIkRlc2NyaXB0aW9uIjogIiIsDQogICAgICAiVmVyc2lvbiI6ICI0LjYuMTU5MC4wIiwNCiAgICAgICJDb25maWd1cmF0aW9uIjogew0KICAgICAgICAiRG9jayI6ICJGaWxsIiwNCiAgICAgICAgIlRhYkluZGV4IjogMSwNCiAgICAgICAgIlBhZGRpbmciOiB7DQogICAgICAgICAgIlRvcCI6IDMsDQogICAgICAgICAgIlJpZ2h0IjogMywNCiAgICAgICAgICAiQm90dG9tIjogMywNCiAgICAgICAgICAiTGVmdCI6IDMNCiAgICAgICAgfSwNCiAgICAgICAgIkF1dG9TY3JvbGxNaW5TaXplIjogew0KICAgICAgICAgICJXaWR0aCI6IDAsDQogICAgICAgICAgIkhlaWdodCI6IDANCiAgICAgICAgfSwNCiAgICAgICAgIlZlcnRpY2FsU2Nyb2xsIjogew0KICAgICAgICAgICJFbmFibGVkIjogdHJ1ZQ0KICAgICAgICB9LA0KICAgICAgICAiSG9yaXpvbnRhbFNjcm9sbCI6IHsNCiAgICAgICAgICAiRW5hYmxlZCI6IHRydWUNCiAgICAgICAgfQ0KICAgICAgfSwNCiAgICAgICJDb250cm9scyI6IFsNCiAgICAgICAgIkdyaWQxIg0KICAgICAgXQ0KICAgIH0sDQogICAgew0KICAgICAgIkd1aWQiOiAiR3JpZDEiLA0KICAgICAgIlR5cGUiOiAiU3lzdGVtLldpbmRvd3MuRm9ybXMuRGF0YUdyaWRWaWV3IiwNCiAgICAgICJEZXNjcmlwdGlvbiI6ICIiLA0KICAgICAgIlZlcnNpb24iOiAiNC42LjE1OTAuMCIsDQogICAgICAiQ29uZmlndXJhdGlvbiI6IHsNCiAgICAgICAgIlNpemUiOiB7DQogICAgICAgICAgIldpZHRoIjogNzU1LA0KICAgICAgICAgICJIZWlnaHQiOiA0MDMNCiAgICAgICAgfSwNCiAgICAgICAgIkxvY2F0aW9uIjogew0KICAgICAgICAgICJYIjogMywNCiAgICAgICAgICAiWSI6IDUyDQogICAgICAgIH0sDQogICAgICAgICJUYWJJbmRleCI6IDEsDQogICAgICAgICJQYWRkaW5nIjogew0KICAgICAgICAgICJUb3AiOiAzLA0KICAgICAgICAgICJSaWdodCI6IDMsDQogICAgICAgICAgIkJvdHRvbSI6IDMsDQogICAgICAgICAgIkxlZnQiOiAzDQogICAgICAgIH0sDQogICAgICAgICJFZGl0TW9kZSI6ICJFZGl0T25LZXlzdHJva2VPckYyIiwNCiAgICAgICAgIlNlbGVjdGlvbk1vZGUiOiAiUm93SGVhZGVyU2VsZWN0IiwNCiAgICAgICAgIlNjcm9sbEJhcnMiOiAiQm90aCIsDQogICAgICAgICJBbGxvd1VzZXJUb0FkZFJvd3MiOiBmYWxzZSwNCiAgICAgICAgIkFsbG93VXNlclRvRGVsZXRlUm93cyI6IHRydWUsDQogICAgICAgICJBbGxvd1VzZXJUb09yZGVyQ29sdW1ucyI6IHRydWUsDQogICAgICAgICJBbGxvd1VzZXJUb1Jlc2l6ZUNvbHVtbnMiOiB0cnVlLA0KICAgICAgICAiQWxsb3dVc2VyVG9SZXNpemVSb3dzIjogdHJ1ZSwNCiAgICAgICAgIkF1dG9TaXplQ29sdW1uc01vZGUiOiAiRGlzcGxheWVkQ2VsbHMiLA0KICAgICAgICAiTXVsdGlTZWxlY3QiOiBmYWxzZSwNCiAgICAgICAgIkNvbHVtbkhlYWRlcnNIZWlnaHRTaXplTW9kZSI6ICJBdXRvU2l6ZSIsDQogICAgICAgICJSb3dIZWFkZXJzV2lkdGhTaXplTW9kZSI6ICJFbmFibGVSZXNpemluZyIsDQogICAgICAgICJBbHRlcm5hdGluZ1Jvd3NEZWZhdWx0Q2VsbFN0eWxlIjogew0KICAgICAgICAgICJCYWNrQ29sb3IiOiAiQXF1YSINCiAgICAgICAgfQ0KICAgICAgfSwNCiAgICAgICJFdmVudHMiOiB7fQ0KICAgIH0NCiAgXQ0KfQ=="; } }
public JObject MappedView { get { return JObject.Parse(System.Text.UTF8Encoding.UTF8.GetString(Convert.FromBase64String(_JSON))); } } 
public System.Windows.Forms.Form VentanaEdicion;
public CView.CtrlStruct VentanaEdicion_cstr;
public object VentanaEdicion_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("VentanasUsoGeneral.VentanaEdicion")[var] = value; 
	return (object)view.CtrlVars("VentanasUsoGeneral.VentanaEdicion")[var];
}
public System.Windows.Forms.Panel PContent;
public CView.CtrlStruct PContent_cstr;
public object PContent_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PContent")[var] = value; 
	return (object)view.CtrlVars("PContent")[var];
}
public System.Windows.Forms.Panel PTop;
public CView.CtrlStruct PTop_cstr;
public object PTop_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PTop")[var] = value; 
	return (object)view.CtrlVars("PTop")[var];
}
public System.Windows.Forms.Button BNuevaFila;
public CView.CtrlStruct BNuevaFila_cstr;
public object BNuevaFila_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("BNuevaFila")[var] = value; 
	return (object)view.CtrlVars("BNuevaFila")[var];
}
public System.Windows.Forms.Button BGuardar;
public CView.CtrlStruct BGuardar_cstr;
public object BGuardar_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("BGuardar")[var] = value; 
	return (object)view.CtrlVars("BGuardar")[var];
}
public System.Windows.Forms.Panel PContenido;
public CView.CtrlStruct PContenido_cstr;
public object PContenido_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("PContenido")[var] = value; 
	return (object)view.CtrlVars("PContenido")[var];
}
public System.Windows.Forms.DataGridView Grid1;
public CView.CtrlStruct Grid1_cstr;
public object Grid1_vars(String var, object value = null) 
{ 
	if (value != null)  view.CtrlVars("Grid1")[var] = value; 
	return (object)view.CtrlVars("Grid1")[var];
}
public object DataSet { get { return (view.vars.ContainsKey("DataSet"))? (object)view.vars["DataSet"]: null; } set { view.vars["DataSet"] = value; } }
public object DataAdapter { get { return (view.vars.ContainsKey("DataAdapter"))? (object)view.vars["DataAdapter"]: null; } set { view.vars["DataAdapter"] = value; } }
public object DataView_Dato_activo { get { return (view.vars.ContainsKey("DataView Dato activo"))? (object)view.vars["DataView Dato activo"]: null; } set { view.vars["DataView Dato activo"] = value; } }
public CView view; 
public CVentanaEdicion (CViewsManager vm) { view = (vm.getFirstView("VentanasUsoGeneral.VentanaEdicion") != null)? vm.getFirstView("VentanasUsoGeneral.VentanaEdicion"): vm.AddView("VentanasUsoGeneral.VentanaEdicion");
VentanaEdicion = (System.Windows.Forms.Form) view.getCtrl("VentanasUsoGeneral.VentanaEdicion");
VentanaEdicion_cstr = view.getCtrlStruct("VentanasUsoGeneral.VentanaEdicion");
PContent = (System.Windows.Forms.Panel) view.getCtrl("PContent");
PContent_cstr = view.getCtrlStruct("PContent");
PTop = (System.Windows.Forms.Panel) view.getCtrl("PTop");
PTop_cstr = view.getCtrlStruct("PTop");
BNuevaFila = (System.Windows.Forms.Button) view.getCtrl("BNuevaFila");
BNuevaFila_cstr = view.getCtrlStruct("BNuevaFila");
BGuardar = (System.Windows.Forms.Button) view.getCtrl("BGuardar");
BGuardar_cstr = view.getCtrlStruct("BGuardar");
PContenido = (System.Windows.Forms.Panel) view.getCtrl("PContenido");
PContenido_cstr = view.getCtrlStruct("PContenido");
Grid1 = (System.Windows.Forms.DataGridView) view.getCtrl("Grid1");
Grid1_cstr = view.getCtrlStruct("Grid1");
 }}

}

